package com.fake.dataworks.service;

import com.fake.dataworks.config.JsonCodec;
import com.fake.dataworks.exception.StudioException;
import com.fake.dataworks.repository.RealtimeRepository;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.Pattern;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;

/** Durable realtime control plane. Remote uncertainty keeps the task's activity lock. */
@Service
public class RealtimeService {
    private static final Set<String> TERMINAL=Set.of("STOPPED","FAILED","FINISHED","CANCELLED");
    private static final Set<String> REMOTE_TERMINAL=Set.of("CANCELED","FAILED","FINISHED");
    private static final Pattern SECRET_OPTION=Pattern.compile("(?is)'(?:password|properties\\.sasl\\.jaas\\.config|properties\\.ssl\\.(?:key|keystore|truststore)\\.password)'\\s*=\\s*'");
    private final RealtimeRepository repo;
    private final ObjectService objects;
    private final DatasourceService sources;
    private final RealtimeSqlCompiler compiler;
    private final FlinkGatewayClient gateway;
    private final JsonCodec json;
    private final TransactionTemplate tx;
    private final boolean polling;
    private final ScheduledExecutorService clock=Executors.newSingleThreadScheduledExecutor(r->new Thread(r,"realtime-clock"));
    private final ExecutorService workers=Executors.newVirtualThreadPerTaskExecutor();
    private final Set<String> working=ConcurrentHashMap.newKeySet();
    private final Map<String,Object> mutexes=new ConcurrentHashMap<>();
    private volatile boolean closing;
    public RealtimeService(RealtimeRepository repo,ObjectService objects,DatasourceService sources,RealtimeSqlCompiler compiler,FlinkGatewayClient gateway,JsonCodec json,TransactionTemplate tx,@Value("${studio.realtime.polling-enabled:true}") boolean polling){this.repo=repo;this.objects=objects;this.sources=sources;this.compiler=compiler;this.gateway=gateway;this.json=json;this.tx=tx;this.polling=polling;}
    @PostConstruct public void start(){if(polling)clock.scheduleWithFixedDelay(this::tick,1000,1500,TimeUnit.MILLISECONDS);}
    @PreDestroy public void close(){closing=true;clock.shutdownNow();workers.shutdownNow();}
    private Object mutex(String id){return mutexes.computeIfAbsent(id,k->new Object());}
    static String now(){return Instant.now().toString();}
    static String id(){return UUID.randomUUID().toString();}
    static String text(Map<String,Object> value,String key){return Objects.toString(value.get(key),"").trim();}
    static int number(Object value,int fallback){return value instanceof Number n?n.intValue():fallback;}
    @SuppressWarnings("unchecked") static Map<String,Object> map(Object value){return value instanceof Map<?,?> m?(Map<String,Object>)m:Map.of();}
    @SuppressWarnings("unchecked") static List<Map<String,Object>> maps(Object value){return value instanceof List<?> list?(List<Map<String,Object>>)list:List.of();}
    private Map<String,Object> cloneMap(Map<String,Object> value){return json.map(json.write(value));}
    private void workspace(String workspace){objects.workspace(workspace);}
    public Map<String,Object> state(String workspace){workspace(workspace);var result=new LinkedHashMap<String,Object>();result.put("schemaVersion",1);result.put("tasks",repo.tasks(workspace));result.put("folders",repo.folders(workspace));result.put("drafts",repo.drafts(workspace));result.put("releases",repo.releases(workspace));result.put("jobs",repo.jobs(workspace).stream().map(this::publicJob).toList());result.put("operations",repo.operations(workspace).stream().map(this::publicOperation).toList());result.put("kafkaSources",sources.list(workspace).stream().filter(s->"KAFKA".equals(s.get("type"))).toList());return result;}
    private static String validName(String value){String name=value.strip();if(name.isEmpty()||name.length()>255||name.contains("/")||name.contains("\\")||name.codePoints().anyMatch(Character::isISOControl))throw StudioException.bad("INVALID_NAME","名称须为1–255字符且不能包含斜杠或控制字符");return name;}
    private Map<String,Object> normalize(String workspace,Map<String,Object> value,String taskId,int revision){
        if(!text(value,"workspaceId").isEmpty()&&!workspace.equals(value.get("workspaceId")))throw StudioException.bad("WORKSPACE_MISMATCH","实时任务不属于当前工作空间");
        var task=cloneMap(value);task.keySet().retainAll(Set.of("id","workspaceId","folderId","name","description","sql","bindings","runtime","revision","updatedAt"));task.put("id",taskId);task.put("workspaceId",workspace);task.put("revision",revision);task.put("updatedAt",now());task.put("name",validName(text(task,"name")));task.putIfAbsent("description","");task.putIfAbsent("sql","");task.putIfAbsent("bindings",List.of());task.putIfAbsent("runtime",Map.of("parallelism",1,"checkpointSeconds",60,"restartAttempts",3,"restartDelaySeconds",10));
        if(!(task.get("bindings") instanceof List<?>)||!(task.get("runtime") instanceof Map<?,?>)||text(task,"sql").length()>200_000)throw StudioException.bad("INVALID_REALTIME_TASK","实时任务配置格式无效或SQL过长");
        var safeBindings=new ArrayList<Map<String,Object>>();for(var binding:maps(task.get("bindings"))){var safe=cloneMap(binding);safe.keySet().retainAll(Set.of("id","role","connector","datasourceId","tableName","physicalTable","topic","fields","format","consumerGroup","startupMode","writeMode","cdcStartupMode","serverId","timezone","eventTimeField","watermarkSeconds","dorisModel","syncDeletes","labelPrefix","feHttpUrls"));safeBindings.add(safe);}task.put("bindings",safeBindings);var runtime=new LinkedHashMap<>(map(task.get("runtime")));runtime.keySet().retainAll(Set.of("parallelism","checkpointSeconds","restartAttempts","restartDelaySeconds"));task.put("runtime",runtime);
        if(SECRET_OPTION.matcher(text(task,"sql")).find())throw StudioException.bad("INLINE_CREDENTIAL_FORBIDDEN","请通过数据源引用注入凭据，SQL中不能保存密码或JAAS认证配置");
        String folder=text(task,"folderId");if(folder.isEmpty())task.put("folderId",null);else if(!repo.folderExists(folder,workspace))throw StudioException.missing("实时目录不存在或不属于当前工作空间");return task;
    }
    public Map<String,Object> createTask(String workspace,Map<String,Object> value){workspace(workspace);return tx.execute(t->{repo.lockWorkspace(workspace);var task=normalize(workspace,value,id(),1);repo.insertTask(task);return task;});}
    public Map<String,Object> saveTask(String workspace,String taskId,Map<String,Object> value,int expected){workspace(workspace);return tx.execute(t->{repo.lockWorkspace(workspace);var old=repo.task(taskId,workspace);checkRevision(old,expected);var task=normalize(workspace,value,taskId,expected+1);repo.updateTask(task,expected);repo.deleteDraft(taskId);return task;});}
    private static void checkRevision(Map<String,Object> task,int expected){if(expected<1||number(task.get("revision"),0)!=expected)throw StudioException.conflict("VERSION_CONFLICT","实时任务已被修改，请重新加载后保存");}
    public Map<String,Object> saveDraft(String workspace,String taskId,Map<String,Object> value,int expected){workspace(workspace);return tx.execute(t->{repo.lockWorkspace(workspace);var old=repo.task(taskId,workspace);checkRevision(old,expected);var draft=normalize(workspace,value,taskId,expected);repo.saveDraft(draft);return draft;});}
    public void deleteDraft(String workspace,String taskId){repo.task(taskId,workspace);repo.deleteDraft(taskId);}
    public void deleteTask(String workspace,String taskId){workspace(workspace);tx.executeWithoutResult(t->{repo.lockWorkspace(workspace);repo.task(taskId,workspace);if(repo.active(taskId).isPresent())throw StudioException.conflict("REALTIME_TASK_ACTIVE","请先完成当前作业或控制操作再删除任务");repo.deleteTask(taskId);});}
    public Map<String,Object> copyTask(String workspace,String taskId,String name){var original=repo.task(taskId,workspace);var copy=cloneMap(original);copy.put("name",name.isEmpty()?text(original,"name")+"_副本":name);return createTask(workspace,copy);}
    public Map<String,Object> folder(String workspace,String folderId,String name){workspace(workspace);return tx.execute(t->{repo.lockWorkspace(workspace);String actual=folderId==null?id():folderId;String normalized=validName(name);if(folderId==null)repo.insertFolder(actual,workspace,normalized);else repo.renameFolder(actual,workspace,normalized);return Map.of("id",actual,"name",normalized);});}
    public void deleteFolder(String workspace,String folderId){workspace(workspace);tx.executeWithoutResult(t->{repo.lockWorkspace(workspace);repo.deleteFolder(folderId,workspace);});}
    public Map<String,Object> publishAsync(String workspace,String taskId,Map<String,Object> task,int expected,String note,String requestId){workspace(workspace);return tx.execute(t->{repo.lockWorkspace(workspace);var duplicate=repo.request(workspace,requestId);if(duplicate.isPresent())return sameRequest(duplicate.get(),"PUBLISH",taskId);var saved=repo.task(taskId,workspace);checkRevision(saved,expected);if(!task.isEmpty())normalize(workspace,task,taskId,expected);var op=newOperation(workspace,taskId,"PUBLISH",requestId);op.put("targetReleaseId",taskId);op.put("payload",Map.of("task",task,"expectedRevision",expected,"note",note));repo.insertOperation(op);return accepted(op);});}
    public Map<String,Object> validateAsync(String workspace,Map<String,Object> task,boolean withPlan,String requestId){workspace(workspace);var draft=normalizeForDebug(workspace,task);return tx.execute(t->{repo.lockWorkspace(workspace);String type=withPlan?"PLAN":"VALIDATE";var duplicate=repo.request(workspace,requestId);if(duplicate.isPresent())return sameRequest(duplicate.get(),type,"");var op=newOperation(workspace,text(draft,"id"),type,requestId);op.put("payload",draft);repo.insertOperation(op);return accepted(op);});}
    public Map<String,Object> publish(String workspace,String taskId,Map<String,Object> value,int expected,String note){workspace(workspace);if(note.length()>4000)throw StudioException.bad("INVALID_RELEASE_NOTE","发布说明过长");return tx.execute(t->{
        repo.lockWorkspace(workspace);var task=repo.task(taskId,workspace);checkRevision(task,expected);if(!value.isEmpty()){task=normalize(workspace,value,taskId,expected+1);repo.updateTask(task,expected);}validateCdc(task);validateBoundSchemas(task);var prepared=compiler.compile(task,"publish");validatePrepared(prepared,true);var release=new LinkedHashMap<String,Object>();release.put("id",id());release.put("taskId",taskId);release.put("workspaceId",workspace);release.put("releaseNo",repo.nextRelease(taskId));release.put("createdAt",now());release.put("note",note);release.put("snapshot",task);release.put("datasourceBindings",prepared.datasourceBindings());release.put("fingerprint",prepared.fingerprint());repo.insertRelease(release);repo.deleteDraft(taskId);return release;
    });}
    public Map<String,Object> validate(String workspace,Map<String,Object> task,boolean withPlan){workspace(workspace);var draft=normalizeForDebug(workspace,task);RealtimeSqlCompiler.Prepared prepared;try{prepared=compiler.compile(draft,"validate");}catch(StudioException e){if(!text(draft,"sql").matches("(?is).*\\b(?:SELECT|WITH)\\b.*"))throw e;prepared=compiler.compilePreview(draft,"validate");}return validatePrepared(prepared,withPlan);}
    private Map<String,Object> normalizeForDebug(String workspace,Map<String,Object> task){return normalize(workspace,task,text(task,"id").isEmpty()?id():text(task,"id"),number(task.get("revision"),1));}
    private Map<String,Object> validatePrepared(RealtimeSqlCompiler.Prepared prepared,boolean withPlan){String session=null;try{gateway.rememberSecrets(prepared.secrets());session=gateway.openSession(prepared.properties());for(String statement:prepared.statements())gateway.execute(session,statement);var result=gateway.execute(session,prepared.explain());return Map.of("valid",true,"errors",List.of(),"plan",withPlan?prepared.redact(planText(result)):"","datasourceBindings",prepared.datasourceBindings(),"fingerprint",prepared.fingerprint());}finally{closeSession(session);}}
    private void validateCdc(Map<String,Object> task){for(var binding:maps(task.get("bindings")))if("MYSQL_CDC".equals(binding.get("connector"))){sources.forWorkspace(text(binding,"datasourceId"),text(task,"workspaceId"));var metadata=sources.cdcMetadata(text(binding,"datasourceId"),text(binding,"physicalTable"));if(!Boolean.TRUE.equals(metadata.get("valid")))throw StudioException.bad("CDC_NOT_READY","MySQL CDC预检失败："+gateway.redact(Objects.toString(metadata.get("issues"),"请检查Binlog与复制权限")));}}
    private void validateBoundSchemas(Map<String,Object> task){for(var binding:maps(task.get("bindings")))sources.validateRealtimeTable(binding,text(task,"workspaceId"));}
    private String planText(Map<String,Object> result){var rows=maps(map(result.get("results")).get("data"));var lines=new ArrayList<String>();for(var row:rows)for(Object field:row.get("fields") instanceof List<?> values?values:List.of())lines.add(Objects.toString(field,""));return lines.isEmpty()?gateway.redact(json.write(result)):String.join("\n",lines);}
    public Map<String,Object> startJob(String workspace,String releaseId,String requestId,String savepointId){workspace(workspace);return tx.execute(t->{repo.lockWorkspace(workspace);var duplicate=repo.request(workspace,requestId);if(duplicate.isPresent())return sameRequest(duplicate.get(),"START",releaseId);var release=repo.release(releaseId,workspace);repo.task(text(release,"taskId"),workspace);compiler.verifyDatasourceBindings(workspace,maps(release.get("datasourceBindings")));var op=newOperation(workspace,text(release,"taskId"),"START",requestId);op.put("targetReleaseId",releaseId);if(!savepointId.isEmpty())op.put("savepoint",findSavepoint(workspace,text(release,"taskId"),savepointId,releaseId));var job=newJob(release,text(op,"id"));op.put("jobId",job.get("id"));repo.acquire(text(release,"taskId"),text(job,"id"),text(op,"id"));repo.insertJob(job);repo.insertOperation(op);return accepted(op);});}
    private Map<String,Object> sameRequest(Map<String,Object> existing,String type,String target){if(!type.equals(existing.get("type"))||!target.isEmpty()&&!target.equals(existing.get("targetReleaseId")))throw StudioException.conflict("REQUEST_CONFLICT","此请求ID已用于不同实时操作");return accepted(existing);}
    private Map<String,Object> newOperation(String workspace,String task,String type,String request){if(request.isEmpty()||request.length()>128)throw StudioException.bad("INVALID_REQUEST_ID","实时控制需要1–128字符请求ID");var op=new LinkedHashMap<String,Object>();op.put("id",id());op.put("workspaceId",workspace);op.put("taskId",task);op.put("type",type);op.put("requestId",request);op.put("status","RUNNING");op.put("phase","QUEUED");op.put("createdAt",now());op.put("updatedAt",now());op.put("rollbackAvailable",false);return op;}
    private Map<String,Object> newJob(Map<String,Object> release,String operation){var task=map(release.get("snapshot"));var job=new LinkedHashMap<String,Object>();job.put("id",id());job.put("workspaceId",release.get("workspaceId"));job.put("taskId",release.get("taskId"));job.put("releaseId",release.get("id"));job.put("releaseNo",release.get("releaseNo"));job.put("taskName",task.get("name"));job.put("jobKind","PRODUCTION");job.put("status","STARTING");job.put("createdAt",now());job.put("updatedAt",now());job.put("startedAt","");job.put("operationId",operation);job.put("pipelineName","sinket_"+text(job,"id").replace("-",""));job.put("attemptId",text(job,"id").replace("-",""));job.put("logs",List.of());job.put("savepoints",List.of());job.put("metrics",Map.of());job.put("checkpoints",Map.of());job.put("checkpointBase",0);job.put("snapshot",cloneMap(task));return job;}
    public Map<String,Object> control(String workspace,String jobId,String action,String requestId,String targetReleaseId){return control(workspace,jobId,action,requestId,targetReleaseId,false);}
    public Map<String,Object> control(String workspace,String jobId,String action,String requestId,String targetReleaseId,boolean allowFreshStart){workspace(workspace);String type=action.toUpperCase(Locale.ROOT);if(!Set.of("CANCEL","STOP","SAVEPOINT","RESTART","UPGRADE").contains(type))throw StudioException.bad("INVALID_ACTION","不支持的实时操作");String mutexTask=text(repo.job(jobId,workspace),"taskId");synchronized(mutex(mutexTask)){return tx.execute(t->{
        repo.lockWorkspace(workspace);var duplicate=repo.request(workspace,requestId);if(duplicate.isPresent()){if("RESTART".equals(type)&&Boolean.TRUE.equals(duplicate.get().get("allowFreshStart"))!=allowFreshStart)throw StudioException.conflict("REQUEST_CONFLICT","此请求ID的重启恢复方式不同");return sameRequest(duplicate.get(),type,targetReleaseId);}var old=repo.job(jobId,workspace);String task=text(old,"taskId");var lock=repo.active(task);if(lock.isPresent()){if(!jobId.equals(lock.get().get("job_id")))throw StudioException.conflict("REALTIME_TASK_ACTIVE","此任务的其他作业仍在运行");var owner=repo.operation(lock.get().get("operation_id").toString(),workspace);if(Set.of("RUNNING","RECOVERING").contains(owner.get("status"))){if(!"CANCEL".equals(type)||"CANCEL".equals(owner.get("type")))throw StudioException.conflict("REALTIME_OPERATION_ACTIVE","请等待或处理当前实时操作");if("UPGRADE".equals(owner.get("type"))&&owner.containsKey("savepoint"))owner.put("rollbackAvailable",true);fail(owner,"OPERATION_CANCELLED","当前操作已转交取消请求，远端作业仍需等待确认终态");}}
        if(Set.of("CANCEL","STOP","SAVEPOINT","UPGRADE").contains(type)&&TERMINAL.contains(old.get("status")))throw StudioException.bad("JOB_NOT_RUNNING","当前作业已结束");
        if("UPGRADE".equals(type)&&targetReleaseId.isEmpty())throw StudioException.bad("RELEASE_REQUIRED","请选择升级目标发布版本");
        String target="UPGRADE".equals(type)?targetReleaseId:text(old,"releaseId");var release=repo.release(target,workspace);if(!task.equals(release.get("taskId")))throw StudioException.bad("WORKSPACE_MISMATCH","目标发布版本不属于此任务");if(Set.of("RESTART","UPGRADE").contains(type))compiler.verifyDatasourceBindings(workspace,maps(release.get("datasourceBindings")));
        if("UPGRADE".equals(type)){var before=repo.release(text(old,"releaseId"),workspace);compiler.verifyDatasourceBindings(workspace,maps(before.get("datasourceBindings")));if(!Objects.equals(canonical(maps(before.get("datasourceBindings"))),canonical(maps(release.get("datasourceBindings")))))throw StudioException.bad("STATE_BINDING_CHANGED","有状态升级须保持数据源连接目标不变，以便从同一保存点回滚旧版本");verifyUpgradeTasks(map(before.get("snapshot")),map(release.get("snapshot")));}
        var op=newOperation(workspace,task,type,requestId);op.put("oldJobId",jobId);op.put("targetReleaseId",target);op.put("oldReleaseId",old.get("releaseId"));op.put("jobId",jobId);op.put("triggerId",id().replace("-",""));if("RESTART".equals(type)){op.put("allowFreshStart",allowFreshStart);op.put("restartMode",allowFreshStart?"FRESH":"SAVEPOINT");if(!allowFreshStart&&TERMINAL.contains(old.get("status"))){var point=latestSavepoint(workspace,task,target).orElseThrow(()->StudioException.conflict("FRESH_START_CONFIRMATION_REQUIRED","此作业没有同发布版本的保存点；全新启动会重新读取来源，请明确确认全新启动"));op.put("savepoint",point);op.put("savepointId",point.get("id"));op.put("restartMode","RESTORE");op.put("phase","OLD_TERMINAL");}}if(lock.isEmpty())repo.acquire(task,jobId,text(op,"id"));else repo.transfer(task,jobId,text(op,"id"));repo.insertOperation(op);old.put("operationId",op.get("id"));old.put("updatedAt",now());repo.saveJob(old);return accepted(op);
    });}}
    public static void verifyUpgradeIdentity(Map<String,Object> before,Map<String,Object> after){
        var a=maps(before.get("bindings"));var b=maps(after.get("bindings"));if(a.size()!=b.size())throw StudioException.bad("STATE_BINDING_CHANGED","有状态升级须保留来源与目标绑定，新增或删除连接请作为新作业启动");
        for(var old:a){var next=b.stream().filter(x->Objects.equals(x.get("id"),old.get("id"))).findFirst().orElseThrow(()->StudioException.bad("STATE_BINDING_CHANGED","有状态升级须保留连接标识"));for(String key:List.of("role","connector","datasourceId","physicalTable","topic","format","consumerGroup","timezone","fields"))if(!Objects.equals(old.get(key),next.get(key)))throw StudioException.bad("STATE_BINDING_CHANGED","有状态升级不能更换物理来源/目标、字段类型或主键，请另建作业");}
    }
    private void verifyUpgradeTasks(Map<String,Object> before,Map<String,Object> after){verifyUpgradeIdentity(before,after);if(!compiler.physicalIdentities(before).equals(compiler.physicalIdentities(after)))throw StudioException.bad("STATE_BINDING_CHANGED","有状态升级须保持自动与手写DDL的物理来源、目标、字段类型和主键不变，请另建作业");}
    private Map<String,Object> findSavepoint(String workspace,String task,String savepointId,String release){for(var job:repo.jobs(workspace))if(task.equals(job.get("taskId")))for(var point:maps(job.get("savepoints")))if(savepointId.equals(point.get("id"))){if(!release.isEmpty()&&!release.equals(point.get("releaseId")))throw StudioException.bad("SAVEPOINT_RELEASE_MISMATCH","恢复启动须使用此发布版本的保存点，跨版本请使用升级");return point;}throw StudioException.missing("保存点不存在");}
    private Optional<Map<String,Object>> latestSavepoint(String workspace,String task,String release){return repo.jobs(workspace).stream().filter(job->task.equals(job.get("taskId"))).flatMap(job->maps(job.get("savepoints")).stream()).filter(point->release.equals(point.get("releaseId"))&&"COMPLETED".equals(point.get("status"))&&!text(point,"path").isEmpty()).max(Comparator.comparing(point->{try{return Instant.parse(text(point,"createdAt"));}catch(RuntimeException e){return Instant.MIN;}}));}
    public Map<String,Object> rollback(String workspace,String operationId,String requestId){workspace(workspace);String mutexTask=text(repo.operation(operationId,workspace),"taskId");synchronized(mutex(mutexTask)){return tx.execute(t->{
        repo.lockWorkspace(workspace);var prior=repo.operation(operationId,workspace);var duplicate=repo.request(workspace,requestId);if(duplicate.isPresent()){if(!operationId.equals(duplicate.get().get("upgradeOperationId")))throw StudioException.conflict("REQUEST_CONFLICT","此请求ID已用于其他升级的回滚");return sameRequest(duplicate.get(),"ROLLBACK",text(prior,"oldReleaseId"));}String task=text(prior,"taskId");var lock=repo.active(task);if(lock.isPresent()&&!text(prior,"jobId").equals(lock.get().get("job_id")))throw StudioException.conflict("REALTIME_TASK_ACTIVE","此任务已有其他活动作业，不能重复回滚");if(!Boolean.TRUE.equals(prior.get("rollbackAvailable")))throw StudioException.bad("ROLLBACK_UNAVAILABLE","此升级没有可用于回滚的保存点");if(lock.isPresent()&&!operationId.equals(lock.get().get("operation_id"))){var owner=repo.operation(lock.get().get("operation_id").toString(),workspace);if(Set.of("RUNNING","RECOVERING").contains(owner.get("status")))throw StudioException.conflict("REALTIME_OPERATION_ACTIVE","此任务的其他操作尚未完成");}
        var op=newOperation(workspace,task,"ROLLBACK",requestId);op.put("targetReleaseId",prior.get("oldReleaseId"));op.put("oldReleaseId",prior.get("oldReleaseId"));op.put("upgradeOperationId",operationId);op.put("oldJobId",prior.get("jobId"));op.put("savepoint",prior.get("savepoint"));op.put("jobId",prior.get("jobId"));if(lock.isEmpty())repo.acquire(task,text(prior,"jobId"),text(op,"id"));else repo.transfer(task,text(prior,"jobId"),text(op,"id"));repo.insertOperation(op);prior.put("rollbackOperationId",op.get("id"));prior.put("updatedAt",now());repo.saveOperation(prior);return accepted(op);
    });}}
    private Map<String,Object> accepted(Map<String,Object> op){var result=new LinkedHashMap<String,Object>();result.put("operationId",op.get("id"));result.put("jobId",op.get("jobId"));if(op.containsKey("previewId"))result.put("previewId",op.get("previewId"));return result;}
    public Map<String,Object> operation(String workspace,String operationId){return publicOperation(repo.operation(operationId,workspace));}
    private Map<String,Object> publicOperation(Map<String,Object> original){var op=cloneMap(original);op.keySet().retainAll(Set.of("id","workspaceId","taskId","type","status","phase","jobId","previewId","createdAt","updatedAt","finishedAt","result","errorCode","message","rollbackAvailable","savepointId","oldJobId","targetReleaseId","oldReleaseId","allowFreshStart","restartMode","rollbackOperationId","rollbackJobId"));return op;}
    public Map<String,Object> detail(String workspace,String jobId){var job=repo.job(jobId,workspace);synchronized(mutex(text(job,"taskId"))){job=repo.job(jobId,workspace);if(!text(job,"flinkJobId").isEmpty())refreshJob(job);return publicJob(repo.job(jobId,workspace));}}
    private Map<String,Object> publicJob(Map<String,Object> original){var job=cloneMap(original);for(String key:List.of("sessionHandle","operationHandle","pipelineName","attemptId","submissionAttempted"))job.remove(key);return job;}
    private void tick(){if(closing)return;try{for(var op:repo.pendingOperations())dispatch("op:"+op.get("id"),()->advanceOperation(text(op,"id"),text(op,"workspaceId")));for(var p:repo.pendingPreviews())dispatch("preview:"+p.get("id"),()->advancePreview(text(p,"id"),text(p,"workspaceId")));for(var job:repo.activeJobs())if(!text(job,"flinkJobId").isEmpty())dispatch("job:"+job.get("id"),()->{synchronized(mutex(text(job,"taskId"))){refreshJob(repo.job(text(job,"id"),text(job,"workspaceId")));}});for(var job:repo.terminalCdcJobs())dispatch("cdc:"+job.get("id"),()->{synchronized(mutex(text(job,"taskId"))){reconcileTerminalCdcJob(repo.job(text(job,"id"),text(job,"workspaceId")));}});for(var job:repo.terminalGatewayCleanupJobs())dispatch("job:"+job.get("id"),()->{synchronized(mutex(text(job,"taskId"))){closeJobSession(repo.job(text(job,"id"),text(job,"workspaceId")));}});}catch(RuntimeException ignored){/* Durable state is retried on the next scan. */}}
    private void dispatch(String key,Runnable action){if(working.add(key))workers.submit(()->{try{action.run();}catch(RuntimeException ignored){}finally{working.remove(key);}});}
    private void advanceOperation(String id,String workspace){var initial=repo.operation(id,workspace);synchronized(mutex(text(initial,"taskId"))){var op=repo.operation(id,workspace);if(!Set.of("RUNNING","RECOVERING").contains(op.get("status")))return;try{switch(text(op,"type")){case "START"->submit(op);case "CANCEL"->cancel(op,false);case "STOP"->stopWithSavepoint(op,false);case "SAVEPOINT"->savepoint(op);case "RESTART"->restart(op);case "UPGRADE"->upgrade(op);case "ROLLBACK"->rollbackAdvance(op);case "PREVIEW"->{/* The bounded query collector owns preview completion. */}case "VALIDATE","PLAN"->{op.put("result",validate(workspace,map(op.get("payload")),"PLAN".equals(op.get("type"))));op.remove("payload");finish(op);}case "PUBLISH"->tx.executeWithoutResult(transaction->{var payload=map(op.get("payload"));op.put("result",publish(workspace,text(op,"taskId"),map(payload.get("task")),number(payload.get("expectedRevision"),0),text(payload,"note")));op.remove("payload");finish(op);});default->fail(op,"INVALID_OPERATION","操作类型无效");}}catch(StudioException e){handleFailure(op,e);}catch(RuntimeException e){handleFailure(op,new StudioException("FLINK_UNAVAILABLE","实时服务暂不可用，正在核实远端状态",502));}}}
    private void phase(Map<String,Object> op,String phase){op.put("phase",phase);op.put("updatedAt",now());repo.saveOperation(op);}
    private void finish(Map<String,Object> op){op.put("status","SUCCESS");op.put("phase","COMPLETED");op.put("finishedAt",now());op.put("updatedAt",now());op.remove("message");op.remove("errorCode");repo.saveOperation(op);}
    private void fail(Map<String,Object> op,String code,String message){op.put("status","FAILED");op.put("errorCode",code);op.put("message",gateway.redact(message));op.put("finishedAt",now());op.put("updatedAt",now());op.remove("payload");repo.saveOperation(op);}
    private void handleFailure(Map<String,Object> op,StudioException error){String phase=text(op,"phase");String jobId=text(op,"jobId");boolean uncertain=Set.of("INITIALIZING","SUBMITTING","RECONCILING","VERIFYING","STOPPING_OLD","WAITING_SAVEPOINT","CANCELLING_OLD","WAITING_CANCEL").contains(phase)&&error.status()>=500 || error.status()==404&&Boolean.TRUE.equals(op.get("savepointRequested"))&&Set.of("STOP","SAVEPOINT","RESTART","UPGRADE").contains(op.get("type"));
        if(uncertain){op.put("status","RECOVERING");op.put("errorCode",error.code());op.put("message","远端请求结果尚未确定，正在对账；不会重复启动作业");op.put("updatedAt",now());repo.saveOperation(op);return;}
        if(op.containsKey("savepoint")&&"UPGRADE".equals(op.get("type")))op.put("rollbackAvailable",true);fail(op,error.code(),error.getMessage());if(!jobId.isEmpty()){var job=repo.job(jobId,text(op,"workspaceId"));if(text(job,"flinkJobId").isEmpty()&&!Boolean.TRUE.equals(job.get("submissionAttempted"))){job.put("status","FAILED");job.put("message",gateway.redact(error.getMessage()));job.put("updatedAt",now());repo.saveJob(job);releaseCdcIfSafe(job);if(!Boolean.TRUE.equals(op.get("rollbackAvailable")))repo.releaseActive(text(op,"taskId"),jobId);}}
    }
    private Map<String,Object> job(Map<String,Object> op){return repo.job(text(op,"jobId"),text(op,"workspaceId"));}
    private void submit(Map<String,Object> op){var job=job(op);String remote=text(job,"flinkJobId");if(!remote.isEmpty()){verifyRunning(op,job);return;}if(Boolean.TRUE.equals(job.get("submissionAttempted"))){if(!text(job,"operationHandle").isEmpty()){try{pollSubmission(op,job);if(!text(job,"flinkJobId").isEmpty()||"FAILED".equals(op.get("status")))return;}catch(StudioException e){if(e.status()!=404)throw e;}}var found=gateway.findJobByName(text(job,"pipelineName"));if(!found.isEmpty()){job.put("flinkJobId",found.getOrDefault("jid",found.get("id")));job.put("updatedAt",now());repo.saveJob(job);phase(op,"VERIFYING");verifyRunning(op,job);}else{op.put("status","RECOVERING");op.put("message","提交结果尚未确定，等待按作业标识对账");phase(op,"RECONCILING");}return;}
        if(!text(job,"sessionHandle").isEmpty()){phase(op,"INITIALIZING");closeJobSession(job);if(!text(job,"sessionHandle").isEmpty())throw new StudioException("GATEWAY_CLEANUP_PENDING","上一次初始化的Gateway会话尚未释放，正在重试清理；不会覆盖句柄",503);}var release=repo.release(text(op,"targetReleaseId"),text(op,"workspaceId"));compiler.verifyDatasourceBindings(text(op,"workspaceId"),maps(release.get("datasourceBindings")));var prepared=compiler.compile(map(release.get("snapshot")),text(job,"attemptId"));verifyPreparedBindings(release,prepared);validateBoundSchemas(map(release.get("snapshot")));repo.reserveCdcServerIds("JOB",text(job,"id"),text(job,"attemptId"),compiler.cdcServerIds(prepared));gateway.rememberSecrets(prepared.secrets());var props=new LinkedHashMap<>(prepared.properties());props.put("pipeline.name",text(job,"pipelineName"));props.put("pipeline.fixed-job-id",text(job,"attemptId"));if(op.containsKey("savepoint")){props.put("execution.state-recovery.path",text(map(op.get("savepoint")),"path"));props.put("execution.state-recovery.claim-mode","NO_CLAIM");props.put("execution.state-recovery.ignore-unclaimed-state","false");job.put("restoredFrom",text(map(op.get("savepoint")),"path"));}
        phase(op,"INITIALIZING");String session=gateway.openSession(props);job.put("sessionHandle",session);job.remove("gatewayCleanupStatus");job.remove("gatewayCleanupMessage");job.put("updatedAt",now());repo.saveJob(job);try{for(String statement:prepared.statements())gateway.execute(session,statement);gateway.execute(session,prepared.explain());job.remove("submissionRejected");job.put("submissionAttempted",true);job.put("updatedAt",now());repo.saveJob(job);phase(op,"SUBMITTING");String handle=gateway.statement(session,prepared.execution());job.put("operationHandle",handle);job.put("updatedAt",now());repo.saveJob(job);}catch(StudioException e){if(!Boolean.TRUE.equals(job.get("submissionAttempted")))closeJobSession(job);throw e;}pollSubmission(op,job);}
    private String submissionError(String session,String handle){String message="Flink提交失败，远端结果仍需核实";try{var result=gateway.result(session,handle,0);message=gateway.redact(json.write(result));}catch(StudioException e){message=gateway.redact(e.getMessage());}return message;}
    private static boolean definiteSqlRejection(String message){return !message.contains("[truncated]")&&message.length()<2900&&message.matches("(?is).*(?:org\\.apache\\.flink\\.table\\.api\\.(?:ValidationException|SqlParserException)|org\\.apache\\.calcite\\.sql\\.parser\\.SqlParseException|org\\.apache\\.flink\\.sql\\.parser\\.impl\\.ParseException).*")&&!message.matches("(?is).*(?:submitJob|executeAsync|AbstractSessionClusterExecutor|RestClusterClient|waitUntilJobInitializationFinished|RestClientException|IOException|java\\.net\\.|TimeoutException|ConnectException|connection reset|JobSubmissionException|could not submit job|Failed to execute sql).*");}
    private void pollSubmission(Map<String,Object> op,Map<String,Object> job){String session=text(job,"sessionHandle"),handle=text(job,"operationHandle");if(handle.isEmpty())return;String status=gateway.status(session,handle);if("ERROR".equals(status)){if(!reconcileIdentity(job).isEmpty()){phase(op,"VERIFYING");verifyRunning(op,job);return;}String message=submissionError(session,handle);if(!definiteSqlRejection(message))throw new StudioException("FLINK_SUBMISSION_UNKNOWN",message,503);job.put("status","FAILED");job.put("submissionRejected",true);job.put("updatedAt",now());repo.saveJob(job);closeJobSession(job);if(!"UPGRADE".equals(op.get("type")))repo.releaseActive(text(op,"taskId"),text(job,"id"));throw StudioException.bad("FLINK_SUBMISSION_FAILED",message);}if(Set.of("CANCELED","CLOSED").contains(status)){if(reconcileIdentity(job).isEmpty())throw new StudioException("FLINK_SUBMISSION_UNKNOWN","SQL操作已关闭，远端提交结果仍需对账",503);phase(op,"VERIFYING");verifyRunning(op,job);return;}var result=gateway.result(session,handle,0);String remote=jobId(result);if(remote.isEmpty())return;job.put("flinkJobId",remote);job.put("updatedAt",now());repo.saveJob(job);phase(op,"VERIFYING");verifyRunning(op,job);}
    private static Object canonical(Object value){if(value instanceof Map<?,?> values){var result=new TreeMap<String,Object>();values.forEach((key,item)->result.put(key.toString(),canonical(item)));return result;}if(value instanceof List<?> values)return values.stream().map(RealtimeService::canonical).toList();if(value instanceof Number valueNumber)return new java.math.BigDecimal(valueNumber.toString()).stripTrailingZeros();return value;}
    static void verifyPreparedBindings(Map<String,Object> release,RealtimeSqlCompiler.Prepared prepared){if(!Objects.equals(canonical(maps(release.get("datasourceBindings"))),canonical(prepared.datasourceBindings())))throw StudioException.conflict("DATASOURCE_BINDING_CHANGED","实际SQL使用的数据源目标已偏离发布快照，请重新发布");}
    static String queryJobId(Map<String,Object> result){for(String key:List.of("jobID","jobId","job-id","jid"))if(result.get(key) instanceof String s&&s.matches("[a-fA-F0-9]{32}"))return s;return "";}
    static String jobId(Map<String,Object> result){String top=queryJobId(result);if(!top.isEmpty())return top;if(!Boolean.FALSE.equals(result.get("isQueryResult")))return "";var body=map(result.get("results"));var columns=maps(body.getOrDefault("columns",body.get("columnInfos")));int index=-1;for(int i=0;i<columns.size();i++)if(Set.of("job_id","jobid").contains(text(columns.get(i),"name").toLowerCase(Locale.ROOT)))index=i;if(index<0)return "";for(var row:maps(body.get("data"))){Object raw=row.get("fields");if(raw instanceof List<?> fields&&fields.size()>index&&fields.get(index) instanceof String s&&s.matches("[a-fA-F0-9]{32}"))return s;}return "";}
    private void verifyRunning(Map<String,Object> op,Map<String,Object> job){if(text(job,"flinkJobId").isEmpty()){pollSubmission(op,job);return;}closeJobSession(job);var remote=gateway.job(text(job,"flinkJobId"));recordRemoteTiming(job,remote);String state=text(remote,"state");if(REMOTE_TERMINAL.contains(state))job.put("remoteTerminalConfirmed",true);if(Set.of("FAILED","CANCELED").contains(state)){job.put("status","FAILED".equals(state)?"FAILED":"STOPPED");job.put("updatedAt",now());repo.saveJob(job);if("UPGRADE".equals(op.get("type"))&&op.containsKey("savepoint"))op.put("rollbackAvailable",true);fail(op,"FLINK_JOB_FAILED","新作业未进入运行状态，远端状态："+state);releaseCdcIfSafe(job);if(!Boolean.TRUE.equals(op.get("rollbackAvailable")))repo.releaseActive(text(op,"taskId"),text(job,"id"));return;}if(!Set.of("RUNNING","FINISHED").contains(state)){phase(op,"VERIFYING");return;}
        var checkpoints=gateway.checkpoints(text(job,"flinkJobId"));if(op.containsKey("savepoint")){var restored=map(map(checkpoints.get("latest")).get("restored"));String expected=text(map(op.get("savepoint")),"path").replaceAll("/+$","");if(!Boolean.TRUE.equals(restored.get("is_savepoint"))||!expected.equals(text(restored,"external_path").replaceAll("/+$","")))throw StudioException.bad("RESTORE_NOT_VERIFIED","作业未证明从指定保存点恢复，请停止后处理");}
        job.put("status",state);if(text(job,"startedAt").isEmpty())job.put("startedAt",now());if("FINISHED".equals(state)&&text(job,"stoppedAt").isEmpty())job.put("stoppedAt",now());job.put("updatedAt",now());job.put("checkpoints",checkpoints);repo.saveJob(job);releaseCdcIfSafe(job);op.put("result",Map.of("jobId",job.get("id"),"flinkJobId",job.get("flinkJobId")));finish(op);if("FINISHED".equals(state))repo.releaseActive(text(op,"taskId"),text(job,"id"));if("ROLLBACK".equals(op.get("type"))&&!text(op,"upgradeOperationId").isEmpty()){var prior=repo.operation(text(op,"upgradeOperationId"),text(op,"workspaceId"));prior.put("rollbackAvailable",false);prior.put("rollbackJobId",job.get("id"));repo.saveOperation(prior);}}
    private String reconcileIdentity(Map<String,Object> job){String remote=text(job,"flinkJobId");if(!remote.isEmpty())return remote;String fixed=text(job,"attemptId");if(fixed.matches("[a-fA-F0-9]{32}"))try{if(!gateway.job(fixed).isEmpty())remote=fixed;}catch(StudioException e){if(e.status()!=404)throw e;}if(remote.isEmpty()){var found=gateway.findJobByName(text(job,"pipelineName"));remote=text(found,"jid");if(remote.isEmpty())remote=text(found,"id");}if(!remote.isEmpty()){job.put("flinkJobId",remote);job.put("updatedAt",now());repo.saveJob(job);}return remote;}
    private void cancel(Map<String,Object> op,boolean oldOnly){var job=oldOnly?repo.job(text(op,"oldJobId"),text(op,"workspaceId")):job(op);String remote=text(job,"flinkJobId");phase(op,"WAITING_CANCEL");if(remote.isEmpty()&&Boolean.TRUE.equals(job.get("submissionAttempted"))&&!Boolean.TRUE.equals(job.get("submissionRejected"))){remote=reconcileIdentity(job);if(remote.isEmpty()&&!text(job,"operationHandle").isEmpty()&&"ERROR".equals(gateway.status(text(job,"sessionHandle"),text(job,"operationHandle")))&&definiteSqlRejection(submissionError(text(job,"sessionHandle"),text(job,"operationHandle")))){job.put("submissionRejected",true);repo.saveJob(job);}if(remote.isEmpty()&&!Boolean.TRUE.equals(job.get("submissionRejected")))throw new StudioException("FLINK_SUBMISSION_UNKNOWN","取消请求正在按固定作业标识对账，未知提交仍保留活动锁",503);}closeJobSession(job);if(remote.isEmpty()){job.put("status","STOPPED");job.put("stoppedAt",now());job.put("updatedAt",now());repo.saveJob(job);}else{String state=text(gateway.job(remote),"state");if(!REMOTE_TERMINAL.contains(state)){gateway.cancel(remote);job.put("status","STOPPING");job.put("updatedAt",now());repo.saveJob(job);return;}job.put("remoteTerminalConfirmed",true);job.put("status","FAILED".equals(state)?"FAILED":"STOPPED");job.put("stoppedAt",now());job.put("updatedAt",now());repo.saveJob(job);}
        releaseCdcIfSafe(job);if(oldOnly&&!gatewayClean(job))throw new StudioException("GATEWAY_CLEANUP_PENDING","旧作业Gateway会话尚未清理，正在重试；不会启动新尝试",503);if(oldOnly)phase(op,"OLD_TERMINAL");else{repo.releaseActive(text(op,"taskId"),text(job,"id"));finish(op);}}
    private void stopWithSavepoint(Map<String,Object> op,boolean upgrading){var old=repo.job(text(op,"oldJobId"),text(op,"workspaceId"));String remote=text(old,"flinkJobId");if(remote.isEmpty())throw new StudioException("FLINK_SUBMISSION_UNKNOWN","旧作业提交结果未知，不能安全生成停止保存点",503);if(!op.containsKey("savepointRequested")){phase(op,"STOPPING_OLD");op.put("savepointRequested",true);repo.saveOperation(op);gateway.stopSavepoint(remote,text(op,"triggerId"));old.put("status","STOPPING");old.put("updatedAt",now());repo.saveJob(old);}var point=gateway.savepointStatus(remote,text(op,"triggerId"));if(!"COMPLETED".equals(text(map(point.get("status")),"id"))){phase(op,"WAITING_SAVEPOINT");return;}var operation=map(point.get("operation"));if(operation.get("failure-cause")!=null)throw StudioException.bad("SAVEPOINT_FAILED","停止保存点生成失败，旧作业状态需核实");String path=text(operation,"location");if(path.isEmpty())throw new StudioException("SAVEPOINT_UNKNOWN","保存点结果缺少路径，正在核实",503);var saved=recordSavepoint(old,path);op.put("savepoint",saved);op.put("savepointId",saved.get("id"));repo.saveOperation(op);String state=text(gateway.job(remote),"state");if(!REMOTE_TERMINAL.contains(state)){phase(op,"WAITING_SAVEPOINT");return;}old.put("remoteTerminalConfirmed",true);old.put("status","STOPPED");old.put("stoppedAt",now());old.put("updatedAt",now());repo.saveJob(old);closeJobSession(old);releaseCdcIfSafe(old);if(upgrading&&!gatewayClean(old))throw new StudioException("GATEWAY_CLEANUP_PENDING","旧作业Gateway会话尚未清理，正在重试；不会启动新尝试",503);if(upgrading)phase(op,"OLD_TERMINAL");else{repo.releaseActive(text(op,"taskId"),text(old,"id"));op.put("result",saved);finish(op);}}
    private Map<String,Object> recordSavepoint(Map<String,Object> job,String path){for(var existing:maps(job.get("savepoints")))if(path.equals(existing.get("path")))return existing;var point=new LinkedHashMap<String,Object>();point.put("id",id());point.put("createdAt",now());point.put("path",path);point.put("releaseId",job.get("releaseId"));point.put("status","COMPLETED");var points=new ArrayList<>(maps(job.get("savepoints")));points.add(point);job.put("savepoints",points);job.put("updatedAt",now());repo.saveJob(job);return point;}
    private void savepoint(Map<String,Object> op){var job=job(op);String remote=text(job,"flinkJobId");if(remote.isEmpty())throw new StudioException("FLINK_SUBMISSION_UNKNOWN","请等待作业提交对账",503);if(!Boolean.TRUE.equals(op.get("savepointRequested"))){op.put("savepointRequested",true);phase(op,"WAITING_SAVEPOINT");gateway.triggerSavepoint(remote,text(op,"triggerId"));}var point=gateway.savepointStatus(remote,text(op,"triggerId"));if(!"COMPLETED".equals(text(map(point.get("status")),"id")))return;var result=map(point.get("operation"));if(result.get("failure-cause")!=null)throw StudioException.bad("SAVEPOINT_FAILED","Flink保存点生成失败");var saved=recordSavepoint(job,text(result,"location"));op.put("savepoint",saved);op.put("savepointId",saved.get("id"));op.put("result",saved);finish(op);}
    private void restart(Map<String,Object> op){
        if(!op.containsKey("newJobId")){
            if("QUEUED".equals(op.get("phase"))){
                var release=repo.release(text(op,"targetReleaseId"),text(op,"workspaceId"));
                compiler.verifyDatasourceBindings(text(op,"workspaceId"),maps(release.get("datasourceBindings")));
                var prepared=compiler.compile(map(release.get("snapshot")),"restart_preflight");
                verifyPreparedBindings(release,prepared);
                validateBoundSchemas(map(release.get("snapshot")));
                validatePrepared(prepared,false);
                phase(op,"PREFLIGHT_OK");
            }
            if(!"OLD_TERMINAL".equals(op.get("phase"))){if(Boolean.TRUE.equals(op.get("allowFreshStart")))cancel(op,true);else stopWithSavepoint(op,true);}
            if(!"OLD_TERMINAL".equals(op.get("phase")))return;
            allocateReplacement(op);
        }
        submit(op);
    }
    private void upgrade(Map<String,Object> op){if(!op.containsKey("newJobId")){if("QUEUED".equals(op.get("phase"))){var release=repo.release(text(op,"targetReleaseId"),text(op,"workspaceId"));var before=repo.release(text(op,"oldReleaseId"),text(op,"workspaceId"));compiler.verifyDatasourceBindings(text(op,"workspaceId"),maps(before.get("datasourceBindings")));if(!Objects.equals(canonical(maps(before.get("datasourceBindings"))),canonical(maps(release.get("datasourceBindings")))))throw StudioException.bad("STATE_BINDING_CHANGED","升级数据源目标偏离旧发布快照，无法安全回滚");verifyUpgradeTasks(map(before.get("snapshot")),map(release.get("snapshot")));var prepared=compiler.compile(map(release.get("snapshot")),"upgrade_preflight");verifyPreparedBindings(release,prepared);validateBoundSchemas(map(release.get("snapshot")));validatePrepared(prepared,false);phase(op,"PREFLIGHT_OK");}stopWithSavepoint(op,true);if(!"OLD_TERMINAL".equals(op.get("phase")))return;allocateReplacement(op);}submit(op);}
    private void allocateReplacement(Map<String,Object> op){tx.executeWithoutResult(t->{repo.lockWorkspace(text(op,"workspaceId"));var release=repo.release(text(op,"targetReleaseId"),text(op,"workspaceId"));var job=newJob(release,text(op,"id"));repo.insertJob(job);op.put("newJobId",job.get("id"));op.put("jobId",job.get("id"));phase(op,"READY_TO_SUBMIT");repo.transfer(text(op,"taskId"),text(job,"id"),text(op,"id"));});}
    private void rollbackAdvance(Map<String,Object> op){
        if(!op.containsKey("newJobId")){
            var failed=repo.job(text(op,"oldJobId"),text(op,"workspaceId"));String remote=text(failed,"flinkJobId");
            if(remote.isEmpty()&&Boolean.TRUE.equals(failed.get("submissionAttempted"))&&!Boolean.TRUE.equals(failed.get("submissionRejected"))){remote=reconcileIdentity(failed);if(remote.isEmpty())throw new StudioException("FLINK_SUBMISSION_UNKNOWN","升级作业结果未知，回滚暂停以避免同时运行",503);}
            closeJobSession(failed);
            if(!remote.isEmpty()){
                String state=text(gateway.job(remote),"state");if(!REMOTE_TERMINAL.contains(state))throw StudioException.conflict("UPGRADE_JOB_ACTIVE","请先取消新版本作业并等待远端终态，再回滚旧版本");
                failed.put("remoteTerminalConfirmed",true);failed.put("status","FAILED".equals(state)?"FAILED":"FINISHED".equals(state)?"FINISHED":"STOPPED");failed.put("updatedAt",now());repo.saveJob(failed);
            }
            releaseCdcIfSafe(failed);
            if(!gatewayClean(failed)){phase(op,"WAITING_CANCEL");throw new StudioException("GATEWAY_CLEANUP_PENDING","升级作业Gateway会话尚未清理，正在重试；不会启动回滚尝试",503);}
            compiler.verifyDatasourceBindings(text(op,"workspaceId"),maps(repo.release(text(op,"targetReleaseId"),text(op,"workspaceId")).get("datasourceBindings")));allocateReplacement(op);
        }
        submit(op);
    }
    private void refreshJob(Map<String,Object> job){closeJobSession(job);try{try{gateway.rememberSecrets(compiler.compile(map(job.get("snapshot")),text(job,"attemptId")).secrets());}catch(StudioException ignored){}String remote=text(job,"flinkJobId");var detail=gateway.job(remote);recordRemoteTiming(job,detail);String state=text(detail,"state");job.put("flinkState",state);if(REMOTE_TERMINAL.contains(state))job.put("remoteTerminalConfirmed",true);if("RUNNING".equals(state))job.put("status","RUNNING");else if(REMOTE_TERMINAL.contains(state)){job.put("status","FAILED".equals(state)?"FAILED":"FINISHED".equals(state)?"FINISHED":"STOPPED");if(text(job,"stoppedAt").isEmpty())job.put("stoppedAt",now());var active=repo.active(text(job,"taskId"));if(active.isPresent()){var owner=repo.operation(active.get().get("operation_id").toString(),text(job,"workspaceId"));if(!Set.of("RUNNING","RECOVERING").contains(owner.get("status"))&&!Boolean.TRUE.equals(owner.get("rollbackAvailable")))repo.releaseActive(text(job,"taskId"),text(job,"id"));}}else if("RESTARTING".equals(state))job.put("status","RESTARTING");
        job.put("checkpoints",gateway.checkpoints(remote));job.put("checkpointConfig",gateway.checkpointConfig(remote));job.put("metrics",gateway.metrics(remote));var logs=gateway.logs(remote);job.put("exceptions",logs.getOrDefault("exceptions",Map.of()));job.put("nodeLogs",logs.getOrDefault("nodes",List.of()));job.put("sharedNodeLogs",Boolean.TRUE.equals(logs.get("sharedNodeLogs")));job.put("logs",logEvents(logs));job.put("updatedAt",now());job.remove("connectionMessage");repo.saveJob(job);releaseCdcIfSafe(job);
    }catch(StudioException e){job.put("connectionMessage",gateway.redact(e.getMessage()));job.put("updatedAt",now());repo.saveJob(job);releaseCdcIfSafe(job);}}
    private List<Map<String,Object>> logEvents(Map<String,Object> logs){String content=gateway.redact(json.write(logs));if(content.length()>16000)content=content.substring(content.length()-16000);return content.equals("{}")?List.of():List.of(Map.of("id","remote","at",now(),"message",content));}
    private static void recordRemoteTiming(Map<String,Object> job,Map<String,Object> remote){for(var entry:Map.of("start-time","startedAt","end-time","stoppedAt").entrySet())if(remote.get(entry.getKey()) instanceof Number number&&number.longValue()>0)job.put(entry.getValue(),Instant.ofEpochMilli(number.longValue()).toString());if(remote.get("duration") instanceof Number number&&number.longValue()>=0)job.put("durationMs",number.longValue());}
    private void closeJobSession(Map<String,Object> job){String session=text(job,"sessionHandle");if(session.isEmpty()||text(job,"flinkJobId").isEmpty()&&Boolean.TRUE.equals(job.get("submissionAttempted"))&&!Boolean.TRUE.equals(job.get("submissionRejected")))return;try{gateway.closeSession(session);job.remove("sessionHandle");job.remove("operationHandle");job.put("gatewayCleanupStatus","COMPLETED");job.remove("gatewayCleanupMessage");}catch(RuntimeException e){job.put("gatewayCleanupStatus","PENDING");job.put("gatewayCleanupMessage",gateway.redact(Objects.toString(e.getMessage(),"Gateway会话清理暂不可用")));}job.put("updatedAt",now());repo.saveJob(job);}
    private boolean releaseCdcIfSafe(Map<String,Object> job){
        if(!TERMINAL.contains(text(job,"status"))||!gatewayClean(job))return false;
        boolean safeUnsubmitted=text(job,"flinkJobId").isEmpty()&&(!Boolean.TRUE.equals(job.get("submissionAttempted"))||Boolean.TRUE.equals(job.get("submissionRejected")));
        if(!safeUnsubmitted&&!Boolean.TRUE.equals(job.get("remoteTerminalConfirmed")))return false;
        repo.releaseCdcServerIds("JOB",text(job,"id"),text(job,"attemptId"));return true;
    }
    private static boolean gatewayClean(Map<String,Object> value){return text(value,"sessionHandle").isEmpty()&&text(value,"operationHandle").isEmpty()&&!"PENDING".equals(value.get("gatewayCleanupStatus"));}
    private void reconcileTerminalCdcJob(Map<String,Object> job){
        closeJobSession(job);
        if(!text(job,"flinkJobId").isEmpty()&&!Boolean.TRUE.equals(job.get("remoteTerminalConfirmed"))){
            String state=text(gateway.job(text(job,"flinkJobId")),"state");if(!REMOTE_TERMINAL.contains(state))return;
            job.put("remoteTerminalConfirmed",true);job.put("flinkState",state);job.put("updatedAt",now());repo.saveJob(job);
        }
        releaseCdcIfSafe(job);
    }
    private void closeSession(String session){if(session!=null&&!session.isEmpty())try{gateway.closeSession(session);}catch(RuntimeException ignored){}}
    public Map<String,Object> preview(String workspace,Map<String,Object> task,String query,String requestId){workspace(workspace);var draft=normalizeForDebug(workspace,task);var prepared=compiler.compilePreview(draft,"preview",query);return tx.execute(t->{repo.lockWorkspace(workspace);var duplicate=repo.request(workspace,requestId);if(duplicate.isPresent())return accepted(duplicate.get());String previewId=id();var op=newOperation(workspace,text(draft,"id"),"PREVIEW",requestId);op.put("previewId",previewId);op.put("jobId",null);op.put("phase","PREVIEW");var p=new LinkedHashMap<String,Object>();p.put("id",previewId);p.put("workspaceId",workspace);p.put("taskId",draft.get("id"));p.put("status","STARTING");p.put("createdAt",now());p.put("updatedAt",now());p.put("deadline",Instant.now().plusSeconds(30).toString());p.put("task",draft);p.put("query",query);p.put("operationId",op.get("id"));p.put("token",0);p.put("rows",List.of());p.put("columns",List.of());p.put("truncated",false);p.put("pipelineName","sinket_preview_"+previewId.replace("-",""));repo.insertPreview(p);repo.insertOperation(op);return accepted(op);});}
    private void advancePreview(String id,String workspace){synchronized(mutex("preview:"+id)){var p=repo.preview(id,workspace);if(!Set.of("STARTING","RUNNING","CANCELLING").contains(p.get("status")))return;try{if(p.containsKey("pendingFinalStatus")||"CANCELLING".equals(p.get("status"))||Instant.now().isAfter(Instant.parse(text(p,"deadline")))){endPreview(p,"CANCELLING".equals(p.get("status"))?"CANCELLED":"SUCCESS",true);return;}String session=text(p,"sessionHandle"),handle=text(p,"operationHandle");if(session.isEmpty()){var prepared=compiler.compilePreview(map(p.get("task")),id.replace("-",""),text(p,"query"));repo.reserveCdcServerIds("PREVIEW",id,id.replace("-",""),compiler.cdcServerIds(prepared));gateway.rememberSecrets(prepared.secrets());var props=new LinkedHashMap<>(prepared.properties());props.put("pipeline.name",text(p,"pipelineName"));props.put("pipeline.fixed-job-id",id.replace("-",""));session=gateway.openSession(props);p.put("sessionHandle",session);p.put("updatedAt",now());repo.savePreview(p);for(String statement:prepared.statements())gateway.execute(session,statement);p.put("querySubmissionAttempted",true);repo.savePreview(p);handle=gateway.statement(session,prepared.queries().getFirst());p.put("operationHandle",handle);p.put("status","RUNNING");repo.savePreview(p);}else if(handle.isEmpty()){endPreview(p,"FAILED",false);return;}
        var result=gateway.result(session,handle,number(p.get("token"),0));String remote=queryJobId(result);if(!remote.isEmpty())p.put("flinkJobId",remote);var results=map(result.get("results"));Object columnInfo=results.getOrDefault("columns",results.get("columnInfos"));if(columnInfo instanceof List<?>)p.put("columns",maps(columnInfo).stream().map(column->Map.of("name",Objects.toString(column.get("name"),""),"type",Objects.toString(column.getOrDefault("logicalType",column.get("type")),""))).toList());var rows=new ArrayList<>(maps(p.get("rows")));for(var row:maps(results.get("data")))if(rows.size()<100)rows.add(row);p.put("rows",rows);p.put("updatedAt",now());if("EOS".equals(result.get("resultType"))){endPreview(p,"SUCCESS",false);return;}if(rows.size()>=100){endPreview(p,"SUCCESS",true);return;}String next=text(result,"nextResultUri");if(!next.isEmpty()){var match=Pattern.compile("/result/(\\d+)").matcher(next);if(match.find())p.put("token",Integer.parseInt(match.group(1)));}repo.savePreview(p);
    }catch(StudioException e){p.put("message",gateway.redact(e.getMessage()));p.put("errorCode",e.code());if(Boolean.TRUE.equals(p.get("querySubmissionAttempted"))&&definiteSqlRejection(e.getMessage()))p.put("submissionRejected",true);endPreview(p,"FAILED",false);}catch(RuntimeException e){p.put("message","查询预览失败，请检查Flink与数据源连接");endPreview(p,"FAILED",false);}}}
    private void endPreview(Map<String,Object> p,String status,boolean truncated){
        p.putIfAbsent("pendingFinalStatus",status);p.putIfAbsent("pendingTruncated",truncated);p.putIfAbsent("pendingMessage",text(p,"message"));p.put("status","CANCELLING");p.put("cleanupStatus","PENDING");p.put("updatedAt",now());repo.savePreview(p);String remote=text(p,"flinkJobId");boolean cleaned=true;
        if(remote.isEmpty()){try{var found=gateway.findJobByName(text(p,"pipelineName"));remote=text(found,"jid");if(remote.isEmpty()&&Boolean.TRUE.equals(p.get("querySubmissionAttempted"))){String fixed=text(p,"id").replace("-","");try{gateway.job(fixed);remote=fixed;}catch(StudioException e){if(e.status()!=404)throw e;}}if(!remote.isEmpty())p.put("flinkJobId",remote);else if(Boolean.TRUE.equals(p.get("querySubmissionAttempted"))&&!Boolean.TRUE.equals(p.get("submissionRejected"))&&text(p,"operationHandle").isEmpty())cleaned=false;}catch(RuntimeException e){cleaned=false;}}
        if(!remote.isEmpty()){try{String remoteState=text(gateway.job(remote),"state");if(!REMOTE_TERMINAL.contains(remoteState)){gateway.cancel(remote);remoteState=text(gateway.job(remote),"state");}if(REMOTE_TERMINAL.contains(remoteState))p.put("remoteTerminalConfirmed",true);cleaned=REMOTE_TERMINAL.contains(remoteState)&&cleaned;}catch(StudioException e){if(e.status()==404){try{String known=remote;boolean absent=maps(gateway.jobsOverview().get("jobs")).stream().noneMatch(job->known.equals(text(job,"jid")));cleaned=absent&&cleaned;}catch(RuntimeException failure){cleaned=false;}}else cleaned=false;}catch(RuntimeException e){cleaned=false;}}
        String session=text(p,"sessionHandle"),operation=text(p,"operationHandle");if(!session.isEmpty()&&!operation.isEmpty())try{gateway.closeOperation(session,operation);previewResourceClosed(p,false);}catch(StudioException e){if(e.status()==404)previewResourceClosed(p,false);else cleaned=false;}catch(RuntimeException e){cleaned=false;}
        if(!session.isEmpty())try{gateway.closeSession(session);previewResourceClosed(p,true);}catch(StudioException e){if(e.status()==404)previewResourceClosed(p,true);else cleaned=false;}catch(RuntimeException e){cleaned=false;}
        if(cleaned&&Boolean.TRUE.equals(p.get("querySubmissionAttempted"))&&!Boolean.TRUE.equals(p.get("remoteTerminalConfirmed"))&&(!Boolean.TRUE.equals(p.get("submissionRejected"))||!text(p,"flinkJobId").isEmpty()))cleaned=false;
        if(cleaned)try{repo.releaseCdcServerIds("PREVIEW",text(p,"id"),text(p,"id").replace("-",""));}catch(RuntimeException e){cleaned=false;}
        if(!cleaned){p.put("status","CANCELLING");p.put("cleanupStatus","PENDING");p.put("message","预览已结束，正在清理远端查询");}
        else{String finalStatus=text(p,"pendingFinalStatus");p.put("status",finalStatus);p.put("cleanupStatus","COMPLETED");p.put("truncated",p.get("pendingTruncated"));p.put("finishedAt",now());p.put("message",p.get("pendingMessage"));p.remove("task");p.remove("query");var op=repo.operation(text(p,"operationId"),text(p,"workspaceId"));if("FAILED".equals(finalStatus))fail(op,text(p,"errorCode"),text(p,"message"));else{op.put("result",Map.of("previewId",p.get("id"),"rowCount",maps(p.get("rows")).size()));finish(op);}}
        p.put("updatedAt",now());repo.savePreview(p);
    }
    private void previewResourceClosed(Map<String,Object> p,boolean session){p.remove("operationHandle");p.put("operationClosed",true);if(session){p.remove("sessionHandle");p.put("sessionClosed",true);}p.put("updatedAt",now());repo.savePreview(p);}
    public Map<String,Object> previewResult(String workspace,String id,int token){var p=repo.preview(id,workspace);int offset=Math.max(0,token)*50;var all=maps(p.get("rows"));var page=all.subList(Math.min(offset,all.size()),Math.min(offset+50,all.size()));var result=new LinkedHashMap<String,Object>();result.put("id",p.get("id"));result.put("status",p.get("status"));result.put("columns",p.get("columns"));result.put("rows",page);result.put("nextToken",offset+50<all.size()?token+1:null);result.put("truncated",p.get("truncated"));for(String key:List.of("message","errorCode","flinkJobId","cleanupStatus"))if(p.containsKey(key))result.put(key,p.get(key));return result;}
    public void cancelPreview(String workspace,String id){synchronized(mutex("preview:"+id)){var p=repo.preview(id,workspace);if(Set.of("STARTING","RUNNING","CANCELLING").contains(p.get("status"))){p.put("status","CANCELLING");p.put("updatedAt",now());repo.savePreview(p);}}}
    public Map<String,Object> importState(String workspace,String importId,Map<String,Object> state){
        workspace(workspace);if(importId.isEmpty()||importId.length()>128)throw StudioException.bad("INVALID_IMPORT_ID","导入需要稳定的请求ID");
        final String checksum;try{checksum=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.write(state).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}
        var datasourceIds=new LinkedHashMap<String,String>();
        tx.executeWithoutResult(t->{
            repo.lockWorkspace(workspace);var old=repo.imported(workspace,importId);if(old.isPresent()){if(!old.get().equals(checksum))throw StudioException.conflict("IMPORT_CONFLICT","相同导入ID的数据已变化");return;}
            for(var kafka:maps(state.get("kafkaSources"))){var input=cloneMap(kafka);input.put("workspaceId",workspace);var existing=sources.list(workspace).stream().filter(s->"KAFKA".equals(s.get("type"))&&Objects.equals(s.get("name"),kafka.get("name"))).findFirst();if(existing.isPresent()&&!kafkaIdentity(existing.get()).equals(kafkaIdentity(input)))throw StudioException.conflict("IMPORT_SOURCE_CONFLICT","同名Kafka数据源的连接目标或认证身份不同，请先重命名旧连接再导入");var saved=existing.orElseGet(()->sources.importKafka(input));datasourceIds.put(text(kafka,"id"),text(saved,"id"));}
            for(var folder:maps(state.get("folders"))){String folderId=text(folder,"id");if(!repo.folderExists(folderId,workspace))repo.insertFolder(folderId,workspace,validName(text(folder,"name")));}
            for(var original:maps(state.get("tasks"))){var task=remapDatasources(original,datasourceIds);String taskId=text(task,"id");if(taskId.isEmpty()||taskId.length()>64)throw StudioException.bad("INVALID_IMPORT","旧任务ID无效");if(repo.existingTask(taskId).isPresent()){if(!workspace.equals(repo.existingTask(taskId).get().get("workspaceId")))throw StudioException.bad("WORKSPACE_MISMATCH","旧任务ID与其他空间冲突");continue;}repo.insertTask(normalize(workspace,task,taskId,1));}
            for(var release:maps(state.get("releases"))){String taskId=text(release,"taskId");repo.task(taskId,workspace);if(repo.releases(workspace).stream().anyMatch(r->Objects.equals(r.get("id"),release.get("id"))))continue;var copy=cloneMap(release);copy.put("workspaceId",workspace);copy.put("snapshot",normalize(workspace,remapDatasources(map(release.get("snapshot")),datasourceIds),taskId,number(map(release.get("snapshot")).get("revision"),1)));try{var prepared=compiler.compile(map(copy.get("snapshot")),"import");copy.put("datasourceBindings",prepared.datasourceBindings());copy.put("fingerprint",prepared.fingerprint());}catch(StudioException e){copy.put("datasourceBindings",List.of());copy.put("importWarning","旧发布需重新校验连接配置后发布");}repo.insertRelease(copy);}
            for(var entry:map(state.get("drafts")).entrySet()){var draft=normalize(workspace,remapDatasources(map(entry.getValue()),datasourceIds),entry.getKey(),1);repo.saveDraft(draft);}
            repo.recordImport(workspace,importId,checksum,now());
        });if(datasourceIds.isEmpty())for(var kafka:maps(state.get("kafkaSources")))sources.list(workspace).stream().filter(s->"KAFKA".equals(s.get("type"))&&Objects.equals(s.get("name"),kafka.get("name"))).findFirst().ifPresent(s->datasourceIds.put(text(kafka,"id"),text(s,"id")));var result=state(workspace);result.put("idMap",datasourceIds);result.put("importWarnings",maps(result.get("kafkaSources")).stream().filter(source->!"PLAINTEXT".equals(source.get("securityProtocol"))&&!Boolean.TRUE.equals(source.get("passwordSet"))).map(source->Map.of("datasourceId",source.get("id"),"errorCode","KAFKA_CREDENTIALS_REQUIRED","message","Kafka SASL凭据未保存，请在数据源管理中补充密码后校验并发布")).toList());return result;
    }
    private static Map<String,String> kafkaIdentity(Map<String,Object> source){String protocol=Objects.toString(source.getOrDefault("securityProtocol","PLAINTEXT"),"").trim();return Map.of("bootstrapServers",Objects.toString(source.getOrDefault("bootstrapServers","localhost:19092"),"").trim().replaceAll("\\s*,\\s*",","),"securityProtocol",protocol,"saslMechanism",Objects.toString(source.getOrDefault("saslMechanism","PLAIN"),"").trim(),"username","PLAINTEXT".equals(protocol)?"":text(source,"username"),"flinkBootstrapServers",text(source,"flinkBootstrapServers").replaceAll("\\s*,\\s*",","));}
    private Map<String,Object> remapDatasources(Map<String,Object> original,Map<String,String> ids){var task=cloneMap(original);for(var binding:maps(task.get("bindings"))){String before=text(binding,"datasourceId");if(ids.containsKey(before))binding.put("datasourceId",ids.get(before));}String sql=text(task,"sql");for(var entry:ids.entrySet()){sql=sql.replace("-- 数据源引用："+entry.getKey(),"-- 数据源引用："+entry.getValue());for(String key:List.of("'studio.datasource-id'","'studio.datasource.id'"))sql=sql.replace(key+" = '"+entry.getKey()+"'",key+" = '"+entry.getValue()+"'");}task.put("sql",sql);return task;}
}
