package com.fake.dataworks.service;

import com.fake.dataworks.config.JsonCodec;
import com.fake.dataworks.exception.StudioException;
import com.fake.dataworks.repository.RealtimeRepository;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.jupiter.api.*;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class RealtimeServiceTest {
    private static final String W="workspace",REMOTE="a".repeat(32),TRIGGER="b".repeat(32);
    RealtimeRepository repo;ObjectService objects;DatasourceService sources;RealtimeSqlCompiler compiler;FlinkGatewayClient gateway;RealtimeService service;
    @BeforeEach void setup(){repo=mock(RealtimeRepository.class);objects=mock(ObjectService.class);sources=mock(DatasourceService.class);compiler=mock(RealtimeSqlCompiler.class);gateway=mock(FlinkGatewayClient.class);service=new RealtimeService(repo,objects,sources,compiler,gateway,new JsonCodec(),new TransactionTemplate(mock(PlatformTransactionManager.class)),false);when(gateway.redact(anyString())).thenAnswer(i->i.getArgument(0));}
    @AfterEach void cleanup(){service.close();}
    Map<String,Object> operation(String type){return new LinkedHashMap<>(Map.of("id","op","workspaceId",W,"taskId","task","type",type,"status","RUNNING","phase","SUBMITTING","jobId","job","targetReleaseId","release"));}
    Map<String,Object> job(){return new LinkedHashMap<>(Map.of("id","job","workspaceId",W,"taskId","task","status","STARTING","releaseId","release","pipelineName","sinket_test","attemptId",REMOTE,"savepoints",List.of()));}
    void bind(Map<String,Object> op,Map<String,Object> job){when(repo.operation("op",W)).thenReturn(op);when(repo.job("job",W)).thenReturn(job);}
    void advance(){ReflectionTestUtils.invokeMethod(service,"advanceOperation","op",W);}
    @Test void versionConflictPreservesSavedTask(){var saved=Map.<String,Object>of("id","task","revision",3);when(repo.task("task",W)).thenReturn(saved);var error=assertThrows(StudioException.class,()->service.saveTask(W,"task",Map.of("name","changed"),2));assertEquals("VERSION_CONFLICT",error.code());verify(repo,never()).updateTask(anyMap(),anyInt());}
    @Test void plaintextCredentialsAreRejectedBeforeMetadataWrites(){var input=Map.<String,Object>of("name","bad","sql","CREATE TABLE s (id INT) WITH ('connector'='jdbc','password'='secret')");assertEquals("INLINE_CREDENTIAL_FORBIDDEN",assertThrows(StudioException.class,()->service.createTask(W,input)).code());verify(repo,never()).insertTask(anyMap());}
    @Test void submittingWithoutHandleNeverResubmitsAndRetainsActivityLock(){var op=operation("START");var job=job();job.put("submissionAttempted",true);bind(op,job);when(gateway.findJobByName("sinket_test")).thenReturn(Map.of());advance();assertEquals("RECOVERING",op.get("status"));assertEquals("RECONCILING",op.get("phase"));verify(gateway,never()).openSession(anyMap());verify(gateway,never()).statement(anyString(),anyString());verify(repo,never()).releaseActive(anyString(),anyString());}
    @Test void persistedGatewayErrorEndsSubmissionInsteadOfRecoveringForever(){var op=operation("START");var job=job();job.put("submissionAttempted",true);job.put("sessionHandle","session");job.put("operationHandle","handle");bind(op,job);when(gateway.status("session","handle")).thenReturn("ERROR");when(gateway.result("session","handle",0)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","org.apache.flink.table.api.ValidationException: semantic failure",502));advance();assertEquals("FAILED",op.get("status"));assertEquals("FLINK_SUBMISSION_FAILED",op.get("errorCode"));assertEquals("FAILED",job.get("status"));verify(repo).releaseActive("task","job");verify(gateway,never()).statement(anyString(),anyString());}
    @Test void restoredSubmissionAdoptsRemoteJobAndValidatesRequestedSavepoint(){var op=operation("START");op.put("savepoint",Map.of("path","file:///opt/flink/state/savepoints/test"));var job=job();job.put("submissionAttempted",true);bind(op,job);when(gateway.findJobByName("sinket_test")).thenReturn(Map.of("jid",REMOTE));when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of("latest",Map.of("restored",Map.of("is_savepoint",true,"external_path","file:///opt/flink/state/savepoints/test"))));advance();assertEquals("SUCCESS",op.get("status"));assertEquals(REMOTE,job.get("flinkJobId"));assertEquals("RUNNING",job.get("status"));verify(gateway,never()).statement(anyString(),anyString());}
    @Test void stopReconcilesPersistedTriggerAndRecordsSavepointOnlyOnce(){var op=operation("STOP");op.put("oldJobId","job");op.put("triggerId",TRIGGER);op.put("savepointRequested",true);var job=job();job.put("flinkJobId",REMOTE);job.put("status","STOPPING");bind(op,job);when(gateway.savepointStatus(REMOTE,TRIGGER)).thenReturn(Map.of("status",Map.of("id","COMPLETED"),"operation",Map.of("location","file:///opt/flink/state/savepoints/test")));when(gateway.job(REMOTE)).thenReturn(Map.of("state","FINISHED"));advance();assertEquals("SUCCESS",op.get("status"));assertEquals(1,RealtimeService.maps(job.get("savepoints")).size());assertEquals("STOPPED",job.get("status"));verify(gateway,never()).stopSavepoint(anyString(),anyString());verify(repo).releaseActive("task","job");}
    @Test void upgradeFailureRetainsRollbackSavepointAndActivity(){var op=operation("UPGRADE");op.put("newJobId","job");op.put("oldReleaseId","old");op.put("savepoint",Map.of("id","point","path","file:///opt/flink/state/savepoints/test"));var job=job();job.put("flinkJobId",REMOTE);bind(op,job);when(gateway.job(REMOTE)).thenReturn(Map.of("state","FAILED"));advance();assertEquals("FAILED",op.get("status"));assertEquals(true,op.get("rollbackAvailable"));verify(repo,never()).releaseActive(anyString(),anyString());}
    @Test void finiteProductionJobCompletesNormallyEvenBeforeFirstPoll(){var op=operation("START");var job=job();job.put("flinkJobId",REMOTE);bind(op,job);when(gateway.job(REMOTE)).thenReturn(Map.of("state","FINISHED"));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of());advance();assertEquals("SUCCESS",op.get("status"));assertEquals("FINISHED",job.get("status"));verify(repo).releaseActive("task","job");}
    @Test void rollbackCannotRunWhileUpgradeJobIsStillActive(){var op=operation("ROLLBACK");op.put("oldJobId","job");var job=job();job.put("flinkJobId",REMOTE);bind(op,job);when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));advance();assertEquals("FAILED",op.get("status"));assertEquals("UPGRADE_JOB_ACTIVE",op.get("errorCode"));verify(gateway,never()).openSession(anyMap());verify(repo,never()).insertJob(anyMap());}
    @Test void cancellationWaitsForRemoteTerminalBeforeReleasingLock(){var op=operation("CANCEL");var job=job();job.put("flinkJobId",REMOTE);bind(op,job);when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"),Map.of("state","CANCELED"));advance();assertEquals("STOPPING",job.get("status"));assertEquals("RUNNING",op.get("status"));verify(repo,never()).releaseActive(anyString(),anyString());advance();assertEquals("SUCCESS",op.get("status"));verify(repo).releaseActive("task","job");}
    @Test void crossVersionPhysicalSourceChangeIsRejectedBeforeStopping(){var binding=Map.<String,Object>of("id","source","role","SOURCE","connector","KAFKA","topic","before","datasourceId","ds");var changed=new LinkedHashMap<>(binding);changed.put("topic","after");assertEquals("STATE_BINDING_CHANGED",assertThrows(StudioException.class,()->RealtimeService.verifyUpgradeIdentity(Map.of("bindings",List.of(binding)),Map.of("bindings",List.of(changed)))).code());}
    @Test void jobIdentityComesOnlyFromDocumentedFieldsOrExplicitInsertResult(){assertEquals(REMOTE,RealtimeService.jobId(Map.of("isQueryResult",false,"results",Map.of("columns",List.of(Map.of("name","job_id")),"data",List.of(Map.of("fields",List.of(REMOTE)))))));assertEquals("",RealtimeService.jobId(Map.of("message","unrelated hex "+REMOTE)));}
    @Test void queryRowsThatLookLikeJobIdsCannotIdentifyOrCancelProductionJobs(){var result=Map.<String,Object>of("isQueryResult",true,"results",Map.of("columns",List.of(Map.of("name","job_id")),"data",List.of(Map.of("fields",List.of(REMOTE)))));assertEquals("",RealtimeService.queryJobId(result));assertEquals("",RealtimeService.jobId(result));}
    @Test void verifyingNetworkFailureKeepsRemoteJobAndActivityRecovering(){var op=operation("START");op.put("phase","VERIFYING");var job=job();job.put("flinkJobId",REMOTE);bind(op,job);when(gateway.job(REMOTE)).thenThrow(new StudioException("FLINK_UNAVAILABLE","network unavailable",503));advance();assertEquals("RECOVERING",op.get("status"));assertEquals(REMOTE,job.get("flinkJobId"));verify(repo,never()).releaseActive(anyString(),anyString());verify(gateway,never()).statement(anyString(),anyString());}
    @Test void unknownSavepointTriggerCannotBeRepeatedOrReleaseActivity(){var op=operation("STOP");op.put("phase","WAITING_SAVEPOINT");op.put("oldJobId","job");op.put("triggerId",TRIGGER);op.put("savepointRequested",true);var job=job();job.put("flinkJobId",REMOTE);bind(op,job);when(gateway.savepointStatus(REMOTE,TRIGGER)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","unknown trigger",404));advance();assertEquals("RECOVERING",op.get("status"));verify(gateway,never()).stopSavepoint(anyString(),anyString());verify(repo,never()).releaseActive(anyString(),anyString());}
    @Test void closedSqlOperationDoesNotProveDetachedProductionJobStopped(){var op=operation("START");var job=job();job.put("submissionAttempted",true);job.put("sessionHandle","session");job.put("operationHandle","handle");bind(op,job);when(gateway.status("session","handle")).thenReturn("CLOSED");when(gateway.findJobByName("sinket_test")).thenReturn(Map.of());advance();assertEquals("RECOVERING",op.get("status"));verify(repo,never()).releaseActive(anyString(),anyString());}
    @Test void preparedSqlIdentityMustMatchImmutableReleaseSnapshot(){var expected=Map.<String,Object>of("id","ds","host","before","port",3306);var prepared=new RealtimeSqlCompiler.Prepared(List.of(),"",List.of(),Map.of(),List.of(Map.of("id","ds","host","after","port",3306)),"",Set.of());assertEquals("DATASOURCE_BINDING_CHANGED",assertThrows(StudioException.class,()->RealtimeService.verifyPreparedBindings(Map.of("datasourceBindings",List.of(expected)),prepared)).code());var identical=new RealtimeSqlCompiler.Prepared(List.of(),"",List.of(),Map.of(),List.of(Map.of("id","ds","host","before","port",3306.0)),"",Set.of());assertDoesNotThrow(()->RealtimeService.verifyPreparedBindings(Map.of("datasourceBindings",List.of(expected)),identical));}
    @Test void previewCleanupWaitsForTerminalAndPreservesSuccessfulResult(){var op=operation("PREVIEW");when(repo.operation("op",W)).thenReturn(op);var preview=new LinkedHashMap<String,Object>(Map.of("id","preview","workspaceId",W,"operationId","op","flinkJobId",REMOTE,"rows",List.of(Map.of("fields",List.of(1))),"sessionHandle","session","operationHandle","handle"));when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"),Map.of("state","CANCELLING"),Map.of("state","CANCELED"));ReflectionTestUtils.invokeMethod(service,"endPreview",preview,"SUCCESS",false);assertEquals("CANCELLING",preview.get("status"));assertEquals("PENDING",preview.get("cleanupStatus"));assertEquals("RUNNING",op.get("status"));ReflectionTestUtils.invokeMethod(service,"endPreview",preview,"CANCELLED",true);assertEquals("SUCCESS",preview.get("status"));assertEquals("COMPLETED",preview.get("cleanupStatus"));assertEquals(false,preview.get("truncated"));assertEquals("SUCCESS",op.get("status"));verify(gateway,times(1)).closeSession("session");assertFalse(preview.containsKey("sessionHandle"));assertFalse(preview.containsKey("operationHandle"));}
    @Test void previewPostWithLostHandleStaysUnknownInsteadOfClaimingCleaned(){var op=operation("PREVIEW");var preview=new LinkedHashMap<String,Object>(Map.of("id",REMOTE,"workspaceId",W,"operationId","op","pipelineName","sinket_preview","rows",List.of(),"sessionHandle","session","querySubmissionAttempted",true));when(gateway.findJobByName("sinket_preview")).thenReturn(Map.of());when(gateway.job(REMOTE)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","not found",404));ReflectionTestUtils.invokeMethod(service,"endPreview",preview,"FAILED",false);assertEquals("CANCELLING",preview.get("status"));assertEquals("PENDING",preview.get("cleanupStatus"));verify(gateway).closeSession("session");verify(repo,never()).operation(anyString(),anyString());}
    @Test void cancelTakesOverUnknownStartAndKeepsLockUntilFixedIdentityIsTerminal(){var owner=operation("START");owner.put("status","RECOVERING");var job=job();job.put("submissionAttempted",true);bind(owner,job);when(repo.active("task")).thenReturn(Optional.of(Map.of("job_id","job","operation_id","op")));when(repo.release("release",W)).thenReturn(Map.of("id","release","taskId","task"));var created=new ArrayList<Map<String,Object>>();doAnswer(invocation->{Map<String,Object> op=invocation.getArgument(0);created.add(op);when(repo.operation(RealtimeService.text(op,"id"),W)).thenReturn(op);return null;}).when(repo).insertOperation(anyMap());var accepted=service.control(W,"job","cancel","cancel-unknown","");var cancel=created.getFirst();assertEquals("FAILED",owner.get("status"));assertEquals("OPERATION_CANCELLED",owner.get("errorCode"));verify(repo).transfer("task","job",accepted.get("operationId").toString());when(gateway.job(REMOTE)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","not yet known",404)).thenReturn(Map.of("state","RUNNING"),Map.of("state","RUNNING"),Map.of("state","CANCELED"));when(gateway.findJobByName("sinket_test")).thenReturn(Map.of());ReflectionTestUtils.invokeMethod(service,"advanceOperation",accepted.get("operationId").toString(),W);assertEquals("RECOVERING",cancel.get("status"));verify(repo,never()).releaseActive(anyString(),anyString());advance();verify(gateway,never()).statement(anyString(),anyString());ReflectionTestUtils.invokeMethod(service,"advanceOperation",accepted.get("operationId").toString(),W);assertEquals("STOPPING",job.get("status"));ReflectionTestUtils.invokeMethod(service,"advanceOperation",accepted.get("operationId").toString(),W);assertEquals("SUCCESS",cancel.get("status"));verify(repo).releaseActive("task","job");}
    @Test void restoreVerificationFailureCanBeCancelledAndRetainsRollbackEntry(){var upgrade=operation("UPGRADE");upgrade.put("phase","VERIFYING");upgrade.put("newJobId","job");upgrade.put("oldReleaseId","old");upgrade.put("savepoint",Map.of("id","point","path","file:///opt/flink/state/savepoints/test"));var job=job();job.put("flinkJobId",REMOTE);bind(upgrade,job);when(repo.active("task")).thenReturn(Optional.of(Map.of("job_id","job","operation_id","op")));when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of());advance();assertEquals("FAILED",upgrade.get("status"));assertEquals("RESTORE_NOT_VERIFIED",upgrade.get("errorCode"));assertEquals(true,upgrade.get("rollbackAvailable"));when(repo.release("release",W)).thenReturn(Map.of("id","release","taskId","task"));var created=new ArrayList<Map<String,Object>>();doAnswer(invocation->{Map<String,Object> op=invocation.getArgument(0);created.add(op);when(repo.operation(RealtimeService.text(op,"id"),W)).thenReturn(op);return null;}).when(repo).insertOperation(anyMap());var accepted=service.control(W,"job","cancel","cancel-unverified","");String cancelId=accepted.get("operationId").toString();ReflectionTestUtils.invokeMethod(service,"advanceOperation",cancelId,W);assertEquals("STOPPING",job.get("status"));verify(repo,never()).releaseActive(anyString(),anyString());when(gateway.job(REMOTE)).thenReturn(Map.of("state","CANCELED"));ReflectionTestUtils.invokeMethod(service,"advanceOperation",cancelId,W);assertEquals("SUCCESS",created.getFirst().get("status"));verify(repo).releaseActive("task","job");assertEquals(true,upgrade.get("rollbackAvailable"));when(repo.active("task")).thenReturn(Optional.empty());var rollback=service.rollback(W,"op","rollback-after-cancel");assertNotNull(rollback.get("operationId"));var rollbackOp=created.getLast();assertEquals("ROLLBACK",rollbackOp.get("type"));assertEquals("old",rollbackOp.get("targetReleaseId"));assertEquals(upgrade.get("savepoint"),rollbackOp.get("savepoint"));}
    @Test void cancellingRecoveringUpgradePreservesItsDurableSavepoint(){var upgrade=operation("UPGRADE");upgrade.put("status","RECOVERING");upgrade.put("savepoint",Map.of("id","point","path","file:///opt/flink/state/savepoints/test"));var job=job();bind(upgrade,job);when(repo.active("task")).thenReturn(Optional.of(Map.of("job_id","job","operation_id","op")));when(repo.release("release",W)).thenReturn(Map.of("id","release","taskId","task"));service.control(W,"job","cancel","cancel-upgrade","");assertEquals("FAILED",upgrade.get("status"));assertEquals(true,upgrade.get("rollbackAvailable"));assertEquals("point",RealtimeService.map(upgrade.get("savepoint")).get("id"));verify(repo,never()).releaseActive(anyString(),anyString());}
    @Test void gatewayErrorAfterAcceptedRemoteSubmissionAdoptsFixedJobInsteadOfUnlocking(){var op=operation("START");var job=job();job.put("submissionAttempted",true);job.put("sessionHandle","session");job.put("operationHandle","handle");bind(op,job);when(gateway.status("session","handle")).thenReturn("ERROR");when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of());advance();assertEquals("SUCCESS",op.get("status"));assertEquals(REMOTE,job.get("flinkJobId"));assertEquals("RUNNING",job.get("status"));verify(repo,never()).releaseActive(anyString(),anyString());verify(gateway,never()).statement(anyString(),anyString());verify(gateway).closeSession("session");}
    @Test void ambiguousGatewayErrorCannotProveJobWasRejected(){var op=operation("START");var job=job();job.put("submissionAttempted",true);job.put("sessionHandle","session");job.put("operationHandle","handle");bind(op,job);when(gateway.status("session","handle")).thenReturn("ERROR");when(gateway.job(REMOTE)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","not yet known",404));when(gateway.findJobByName("sinket_test")).thenReturn(Map.of());when(gateway.result("session","handle",0)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","TimeoutException: submitJob response lost",502));advance();assertEquals("RECOVERING",op.get("status"));assertFalse(Boolean.TRUE.equals(job.get("submissionRejected")));verify(repo,never()).releaseActive(anyString(),anyString());}
    @Test void manualPhysicalIdentityChangeIsRejectedBeforeCreatingUpgradeOperation(){var job=job();job.put("status","RUNNING");when(repo.job("job",W)).thenReturn(job);var before=Map.<String,Object>of("id","release","taskId","task","snapshot",Map.of("sql","before","bindings",List.of()),"datasourceBindings",List.of());var after=Map.<String,Object>of("id","next","taskId","task","snapshot",Map.of("sql","after","bindings",List.of()),"datasourceBindings",List.of());when(repo.release("release",W)).thenReturn(before);when(repo.release("next",W)).thenReturn(after);when(compiler.physicalIdentities(RealtimeService.map(before.get("snapshot")))).thenReturn(Map.of("source","topic-before"));when(compiler.physicalIdentities(RealtimeService.map(after.get("snapshot")))).thenReturn(Map.of("source","topic-after"));assertEquals("STATE_BINDING_CHANGED",assertThrows(StudioException.class,()->service.control(W,"job","upgrade","different-physical","next")).code());verify(repo,never()).insertOperation(anyMap());verify(gateway,never()).stopSavepoint(anyString(),anyString());}
    @Test void detailPreservesStructuredExceptionsAndLogNodeAttribution(){var job=job();job.put("flinkJobId",REMOTE);job.put("snapshot",Map.of());when(repo.job("job",W)).thenReturn(job);when(compiler.compile(anyMap(),anyString())).thenReturn(new RealtimeSqlCompiler.Prepared(List.of(),"",List.of(),Map.of(),List.of(),"",Set.of()));when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of());when(gateway.checkpointConfig(REMOTE)).thenReturn(Map.of());when(gateway.metrics(REMOTE)).thenReturn(Map.of());var exceptions=Map.<String,Object>of("root-exception","business failure","all-exceptions",List.of(Map.of("task","source","exception","failure")));var node=Map.<String,Object>of("node","taskmanager-1","file","flink.log","content","shared logs","containsJobId",true,"truncated",false);when(gateway.logs(REMOTE)).thenReturn(Map.of("exceptions",exceptions,"nodes",List.of(node),"sharedNodeLogs",true));var detail=service.detail(W,"job");assertEquals(exceptions,detail.get("exceptions"));assertEquals(List.of(node),detail.get("nodeLogs"));assertEquals(true,detail.get("sharedNodeLogs"));}
    @Test void cancellationDuringPreviewSubmissionCannotBeOverwrittenByStaleRunningSnapshot() throws Exception {
        var codec=new JsonCodec();var stored=new AtomicReference<Map<String,Object>>(new LinkedHashMap<>());stored.get().putAll(Map.of("id",REMOTE,"workspaceId",W,"taskId","task","operationId","op","status","STARTING","task",Map.of(),"query","SELECT 1","pipelineName","sinket_preview","rows",List.of(),"deadline",java.time.Instant.now().plusSeconds(30).toString()));stored.get().put("token",0);
        when(repo.preview(REMOTE,W)).thenAnswer(invocation->codec.map(codec.write(stored.get())));doAnswer(invocation->{stored.set(codec.map(codec.write(invocation.getArgument(0))));return null;}).when(repo).savePreview(anyMap());var op=operation("PREVIEW");when(repo.operation("op",W)).thenReturn(op);when(compiler.compilePreview(anyMap(),anyString(),anyString())).thenReturn(new RealtimeSqlCompiler.Prepared(List.of(),"",List.of("SELECT 1"),Map.of(),List.of(),"",Set.of()));when(gateway.openSession(anyMap())).thenReturn("session");when(gateway.result("session","handle",0)).thenReturn(Map.of("resultType","PAYLOAD","results",Map.of("data",List.of())));when(gateway.findJobByName("sinket_preview")).thenReturn(Map.of());when(gateway.job(REMOTE)).thenReturn(Map.of("state","CANCELED"));
        var submitting=new CountDownLatch(1);var releaseSubmit=new CountDownLatch(1);var cancelling=new CountDownLatch(1);when(gateway.statement("session","SELECT 1")).thenAnswer(invocation->{submitting.countDown();assertTrue(releaseSubmit.await(2,TimeUnit.SECONDS));return "handle";});
        try(var executor=Executors.newVirtualThreadPerTaskExecutor()){
            var submit=executor.submit(()->ReflectionTestUtils.invokeMethod(service,"advancePreview",REMOTE,W));assertTrue(submitting.await(2,TimeUnit.SECONDS));var cancel=executor.submit(()->{cancelling.countDown();service.cancelPreview(W,REMOTE);});assertTrue(cancelling.await(2,TimeUnit.SECONDS));try{assertThrows(TimeoutException.class,()->cancel.get(100,TimeUnit.MILLISECONDS));}finally{releaseSubmit.countDown();}submit.get(2,TimeUnit.SECONDS);cancel.get(2,TimeUnit.SECONDS);
        }
        assertEquals("CANCELLING",stored.get().get("status"));ReflectionTestUtils.invokeMethod(service,"advancePreview",REMOTE,W);assertEquals("CANCELLED",stored.get().get("status"));assertEquals("COMPLETED",stored.get().get("cleanupStatus"));assertEquals("SUCCESS",op.get("status"));verify(gateway,times(1)).statement("session","SELECT 1");
    }
    @Test void successfulRollbackDisablesOldEntryAndRejectsSecondProductionAttempt(){var upgrade=operation("UPGRADE");upgrade.put("id","upgrade");upgrade.put("status","FAILED");upgrade.put("oldReleaseId","old");upgrade.put("rollbackAvailable",true);upgrade.put("jobId","failed-target");when(repo.operation("upgrade",W)).thenReturn(upgrade);var rollback=operation("ROLLBACK");rollback.put("upgradeOperationId","upgrade");rollback.put("targetReleaseId","old");rollback.put("newJobId","job");var job=job();job.put("flinkJobId",REMOTE);bind(rollback,job);when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of());advance();assertEquals("SUCCESS",rollback.get("status"));assertEquals(false,upgrade.get("rollbackAvailable"));assertEquals("job",upgrade.get("rollbackJobId"));when(repo.active("task")).thenReturn(Optional.of(Map.of("job_id","job","operation_id","op")));assertEquals("REALTIME_TASK_ACTIVE",assertThrows(StudioException.class,()->service.rollback(W,"upgrade","second-rollback")).code());verify(repo,never()).insertOperation(anyMap());verify(repo,never()).transfer(anyString(),anyString(),anyString());verify(gateway,never()).statement(anyString(),anyString());}
    @Test void staleRollbackAvailabilityCannotStealRunningJobOwnedByCompletedOperation(){var upgrade=operation("UPGRADE");upgrade.put("rollbackAvailable",true);upgrade.put("oldReleaseId","old");upgrade.put("jobId","failed-target");when(repo.operation("op",W)).thenReturn(upgrade);when(repo.active("task")).thenReturn(Optional.of(Map.of("job_id","previous-rollback-job","operation_id","completed-rollback")));when(repo.operation("completed-rollback",W)).thenReturn(Map.of("status","SUCCESS"));assertEquals("REALTIME_TASK_ACTIVE",assertThrows(StudioException.class,()->service.rollback(W,"op","another-request")).code());verify(repo,never()).insertOperation(anyMap());verify(repo,never()).transfer(anyString(),anyString(),anyString());}
    @Test void retryOfSuccessfulRollbackReturnsOriginalOperationBeforeAvailabilityCheck(){var upgrade=operation("UPGRADE");upgrade.put("id","upgrade");upgrade.put("rollbackAvailable",false);upgrade.put("oldReleaseId","old");when(repo.operation("upgrade",W)).thenReturn(upgrade);var completed=operation("ROLLBACK");completed.put("id","original-rollback");completed.put("status","SUCCESS");completed.put("targetReleaseId","old");completed.put("upgradeOperationId","upgrade");when(repo.request(W,"same-request")).thenReturn(Optional.of(completed));assertEquals("original-rollback",service.rollback(W,"upgrade","same-request").get("operationId"));verify(repo,never()).insertOperation(anyMap());verify(repo,never()).transfer(anyString(),anyString(),anyString());}
    @Test void defaultRunningRestartStopsWithSavepointAndVerifiesStrictRestore(){
        var op=operation("RESTART");op.put("phase","QUEUED");op.put("oldJobId","job");op.put("triggerId",TRIGGER);op.put("allowFreshStart",false);
        var old=job();old.put("status","RUNNING");old.put("flinkJobId",REMOTE);bind(op,old);
        String replacement="c".repeat(32),path="file:///opt/flink/state/savepoints/restart";
        var binding=Map.<String,Object>of("id","source","connector","MYSQL_CDC","role","SOURCE");
        var snapshot=Map.<String,Object>of("name","stateful","workspaceId",W,"bindings",List.of(binding));
        var release=Map.<String,Object>of("id","release","taskId","task","workspaceId",W,"releaseNo",1,"snapshot",snapshot,"datasourceBindings",List.of());
        when(repo.release("release",W)).thenReturn(release);
        var created=new ArrayList<Map<String,Object>>();
        doAnswer(invocation->{Map<String,Object> next=invocation.getArgument(0);created.add(next);when(repo.job(RealtimeService.text(next,"id"),W)).thenReturn(next);return null;}).when(repo).insertJob(anyMap());
        var persistedPhases=new ArrayList<String>();
        doAnswer(invocation->{persistedPhases.add(RealtimeService.text(invocation.getArgument(0),"phase"));return null;}).when(repo).saveOperation(anyMap());
        when(gateway.stopSavepoint(REMOTE,TRIGGER)).thenAnswer(invocation->{assertEquals("PREFLIGHT_OK",persistedPhases.getFirst());return TRIGGER;});
        when(gateway.savepointStatus(REMOTE,TRIGGER)).thenReturn(Map.of("status",Map.of("id","COMPLETED"),"operation",Map.of("location",path)));
        when(gateway.job(REMOTE)).thenReturn(Map.of("state","FINISHED"));
        var prepared=new RealtimeSqlCompiler.Prepared(List.of(),"INSERT INTO target SELECT * FROM source",List.of(),Map.of(),List.of(),"",Set.of());
        when(compiler.compile(anyMap(),anyString())).thenReturn(prepared);
        when(gateway.openSession(anyMap())).thenReturn("preflight","session");
        when(gateway.execute(anyString(),anyString())).thenReturn(Map.of());
        when(gateway.statement(eq("session"),anyString())).thenReturn("handle");when(gateway.status("session","handle")).thenReturn("FINISHED");
        when(gateway.result("session","handle",0)).thenReturn(Map.of("jobID",replacement));when(gateway.job(replacement)).thenReturn(Map.of("state","RUNNING"));
        when(gateway.checkpoints(replacement)).thenReturn(Map.of("latest",Map.of("restored",Map.of("is_savepoint",true,"external_path",path))));
        advance();
        assertEquals("SUCCESS",op.get("status"));assertEquals("STOPPED",old.get("status"));assertEquals(1,RealtimeService.maps(old.get("savepoints")).size());
        assertEquals("RUNNING",created.getFirst().get("status"));assertEquals(path,created.getFirst().get("restoredFrom"));
        var properties=org.mockito.ArgumentCaptor.forClass(Map.class);verify(gateway,times(2)).openSession(properties.capture());
        var runtimeProperties=properties.getAllValues().getLast();assertEquals(path,runtimeProperties.get("execution.state-recovery.path"));
        assertEquals("NO_CLAIM",runtimeProperties.get("execution.state-recovery.claim-mode"));assertEquals("false",runtimeProperties.get("execution.state-recovery.ignore-unclaimed-state"));
        var ordered=inOrder(compiler,sources,gateway);
        ordered.verify(compiler).verifyDatasourceBindings(W,List.of());ordered.verify(compiler).compile(snapshot,"restart_preflight");
        ordered.verify(sources).validateRealtimeTable(binding,W);ordered.verify(gateway).execute("preflight",prepared.explain());
        ordered.verify(gateway).stopSavepoint(REMOTE,TRIGGER);
        var registrationOrder=inOrder(repo);registrationOrder.verify(repo).releaseCdcServerIds("JOB","job",REMOTE);
        registrationOrder.verify(repo).reserveCdcServerIds("JOB",RealtimeService.text(created.getFirst(),"id"),RealtimeService.text(created.getFirst(),"attemptId"),List.of());
        verify(gateway).closeSession("preflight");verify(gateway,never()).cancel(anyString());
    }
    @Test void terminalRestartWithoutSavepointRequiresExplicitFreshStartConfirmation(){var old=job();old.put("status","STOPPED");when(repo.job("job",W)).thenReturn(old);when(repo.release("release",W)).thenReturn(Map.of("id","release","taskId","task"));assertEquals("FRESH_START_CONFIRMATION_REQUIRED",assertThrows(StudioException.class,()->service.control(W,"job","restart","restart-without-point","")).code());verify(repo,never()).insertOperation(anyMap());verify(repo,never()).acquire(anyString(),anyString(),anyString());}
    @Test void terminalRestartSelectsMostRecentSameReleaseSavepoint(){var old=job();old.put("status","STOPPED");var older=Map.<String,Object>of("id","older","path","file:///opt/flink/state/savepoints/older","releaseId","release","status","COMPLETED","createdAt","2026-10-01T00:00:00Z");var latest=Map.<String,Object>of("id","latest","path","file:///opt/flink/state/savepoints/latest","releaseId","release","status","COMPLETED","createdAt","2026-10-01T00:01:00Z");old.put("savepoints",List.of(older,latest));when(repo.job("job",W)).thenReturn(old);when(repo.jobs(W)).thenReturn(List.of(old));when(repo.release("release",W)).thenReturn(Map.of("id","release","taskId","task"));service.control(W,"job","restart","restart-from-point","");var created=org.mockito.ArgumentCaptor.forClass(Map.class);verify(repo).insertOperation(created.capture());assertEquals(latest,created.getValue().get("savepoint"));assertEquals("RESTORE",created.getValue().get("restartMode"));assertEquals("OLD_TERMINAL",created.getValue().get("phase"));assertEquals(false,created.getValue().get("allowFreshStart"));}
    @Test void explicitFreshRestartBypassesSavepointWhileKeepingTerminationCheck(){
        var op=operation("RESTART");op.put("phase","QUEUED");op.put("oldJobId","job");op.put("triggerId",TRIGGER);op.put("allowFreshStart",true);
        var old=job();old.put("status","RUNNING");old.put("flinkJobId",REMOTE);bind(op,old);
        when(repo.release("release",W)).thenReturn(Map.of("id","release","taskId","task","snapshot",Map.of("workspaceId",W),"datasourceBindings",List.of()));
        var prepared=new RealtimeSqlCompiler.Prepared(List.of(),"INSERT INTO target SELECT * FROM source",List.of(),Map.of(),List.of(),"",Set.of());
        when(compiler.compile(anyMap(),eq("restart_preflight"))).thenReturn(prepared);when(gateway.openSession(anyMap())).thenReturn("preflight");
        when(gateway.execute("preflight",prepared.explain())).thenReturn(Map.of());when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));
        advance();assertEquals("WAITING_CANCEL",op.get("phase"));assertEquals("STOPPING",old.get("status"));
        var ordered=inOrder(gateway);ordered.verify(gateway).execute("preflight",prepared.explain());ordered.verify(gateway).cancel(REMOTE);
        verify(gateway,never()).stopSavepoint(anyString(),anyString());verify(repo,never()).insertJob(anyMap());
        var terminal=job();terminal.put("status","STOPPED");when(repo.job("job",W)).thenReturn(terminal);when(repo.release("release",W)).thenReturn(Map.of("id","release","taskId","task"));
        service.control(W,"job","restart","confirmed-fresh","",true);var created=org.mockito.ArgumentCaptor.forClass(Map.class);verify(repo).insertOperation(created.capture());
        assertEquals(true,created.getValue().get("allowFreshStart"));assertEquals("FRESH",created.getValue().get("restartMode"));assertFalse(created.getValue().containsKey("savepoint"));
    }
    @Test void queuedRestartWithDatasourceDriftPreservesRunningJobAndActivity(){
        var op=operation("RESTART");op.put("phase","QUEUED");op.put("oldJobId","job");op.put("triggerId",TRIGGER);
        var old=job();old.put("status","RUNNING");old.put("flinkJobId",REMOTE);bind(op,old);
        when(repo.release("release",W)).thenReturn(Map.of("snapshot",Map.of("workspaceId",W),"datasourceBindings",List.of()));
        doThrow(StudioException.conflict("DATASOURCE_BINDING_CHANGED","数据源目标已变化")).when(compiler).verifyDatasourceBindings(W,List.of());
        advance();assertEquals("FAILED",op.get("status"));assertEquals("DATASOURCE_BINDING_CHANGED",op.get("errorCode"));assertEquals("RUNNING",old.get("status"));
        verify(compiler,never()).compile(anyMap(),anyString());verify(gateway,never()).openSession(anyMap());
        verify(gateway,never()).stopSavepoint(anyString(),anyString());verify(gateway,never()).cancel(anyString());
        verify(repo,never()).insertJob(anyMap());verify(repo,never()).releaseActive(anyString(),anyString());verify(repo,never()).saveJob(anyMap());
    }
    @Test void queuedFreshRestartWithSchemaDriftPreservesRunningJobAndActivity(){
        var op=operation("RESTART");op.put("phase","QUEUED");op.put("oldJobId","job");op.put("allowFreshStart",true);
        var old=job();old.put("status","RUNNING");old.put("flinkJobId",REMOTE);bind(op,old);
        var binding=Map.<String,Object>of("id","sink","connector","MYSQL_JDBC","role","SINK");var snapshot=Map.<String,Object>of("workspaceId",W,"bindings",List.of(binding));
        when(repo.release("release",W)).thenReturn(Map.of("snapshot",snapshot,"datasourceBindings",List.of()));
        when(compiler.compile(snapshot,"restart_preflight")).thenReturn(new RealtimeSqlCompiler.Prepared(List.of(),"INSERT INTO target SELECT * FROM source",List.of(),Map.of(),List.of(),"",Set.of()));
        doThrow(StudioException.bad("TARGET_SCHEMA_MISMATCH","目标表字段已变化")).when(sources).validateRealtimeTable(binding,W);
        advance();assertEquals("FAILED",op.get("status"));assertEquals("TARGET_SCHEMA_MISMATCH",op.get("errorCode"));assertEquals("RUNNING",old.get("status"));
        verify(gateway,never()).openSession(anyMap());verify(gateway,never()).stopSavepoint(anyString(),anyString());verify(gateway,never()).cancel(anyString());
        verify(repo,never()).insertJob(anyMap());verify(repo,never()).releaseActive(anyString(),anyString());verify(repo,never()).saveJob(anyMap());
    }
    @Test void queuedRestartWithExplainFailurePreservesRunningJobAndClosesPreflightSession(){
        var op=operation("RESTART");op.put("phase","QUEUED");op.put("oldJobId","job");op.put("triggerId",TRIGGER);
        var old=job();old.put("status","RUNNING");old.put("flinkJobId",REMOTE);bind(op,old);var snapshot=Map.<String,Object>of("workspaceId",W);
        when(repo.release("release",W)).thenReturn(Map.of("snapshot",snapshot,"datasourceBindings",List.of()));
        var prepared=new RealtimeSqlCompiler.Prepared(List.of("CREATE TEMPORARY VIEW source AS SELECT 1"),"INSERT INTO target SELECT * FROM source",List.of(),Map.of(),List.of(),"",Set.of());
        when(compiler.compile(snapshot,"restart_preflight")).thenReturn(prepared);when(gateway.openSession(anyMap())).thenReturn("preflight");
        when(gateway.execute("preflight",prepared.explain())).thenThrow(StudioException.bad("FLINK_SQL_INVALID","SQL执行计划无效"));
        advance();assertEquals("FAILED",op.get("status"));assertEquals("FLINK_SQL_INVALID",op.get("errorCode"));assertEquals("QUEUED",op.get("phase"));assertEquals("RUNNING",old.get("status"));
        verify(gateway).execute("preflight",prepared.statements().getFirst());verify(gateway).closeSession("preflight");
        verify(gateway,never()).statement(anyString(),anyString());verify(gateway,never()).stopSavepoint(anyString(),anyString());verify(gateway,never()).cancel(anyString());
        verify(repo,never()).insertJob(anyMap());verify(repo,never()).releaseActive(anyString(),anyString());verify(repo,never()).saveJob(anyMap());
    }
    @Test void persistedRestartPreflightResumesWithoutRecheckingOrRepeatingSavepointTrigger(){
        var op=operation("RESTART");op.put("phase","PREFLIGHT_OK");op.put("oldJobId","job");op.put("triggerId",TRIGGER);
        var old=job();old.put("status","RUNNING");old.put("flinkJobId",REMOTE);bind(op,old);
        service.close();service=new RealtimeService(repo,objects,sources,compiler,gateway,new JsonCodec(),new TransactionTemplate(mock(PlatformTransactionManager.class)),false);
        when(gateway.stopSavepoint(REMOTE,TRIGGER)).thenReturn(TRIGGER);when(gateway.savepointStatus(REMOTE,TRIGGER)).thenReturn(Map.of("status",Map.of("id","IN_PROGRESS")));
        advance();advance();assertEquals("RUNNING",op.get("status"));assertEquals("WAITING_SAVEPOINT",op.get("phase"));assertEquals("STOPPING",old.get("status"));
        verify(compiler,never()).verifyDatasourceBindings(anyString(),anyList());verify(compiler,never()).compile(anyMap(),anyString());
        verify(sources,never()).validateRealtimeTable(anyMap(),anyString());verify(gateway,never()).openSession(anyMap());verify(gateway,never()).execute(anyString(),anyString());
        verify(gateway,times(1)).stopSavepoint(REMOTE,TRIGGER);verify(gateway,times(2)).savepointStatus(REMOTE,TRIGGER);
        verify(repo,never()).insertJob(anyMap());verify(repo,never()).releaseActive(anyString(),anyString());
    }
    @Test void cleanupPersistsClosedResourcesBeforeRemoteJobReachesTerminal(){var op=operation("PREVIEW");when(repo.operation("op",W)).thenReturn(op);var preview=new LinkedHashMap<String,Object>(Map.of("id","preview","workspaceId",W,"operationId","op","flinkJobId",REMOTE,"rows",List.of(),"sessionHandle","session","operationHandle","handle"));when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"),Map.of("state","CANCELLING"),Map.of("state","CANCELED"));doNothing().doThrow(new StudioException("FLINK_REQUEST_FAILED","SessionNotFoundException",502)).when(gateway).closeSession("session");ReflectionTestUtils.invokeMethod(service,"endPreview",preview,"SUCCESS",false);assertEquals("PENDING",preview.get("cleanupStatus"));assertEquals(true,preview.get("sessionClosed"));assertEquals(true,preview.get("operationClosed"));assertFalse(preview.containsKey("sessionHandle"));assertFalse(preview.containsKey("operationHandle"));ReflectionTestUtils.invokeMethod(service,"endPreview",preview,"CANCELLED",true);assertEquals("COMPLETED",preview.get("cleanupStatus"));assertEquals("SUCCESS",preview.get("status"));verify(gateway,times(1)).closeSession("session");verify(gateway,times(1)).closeOperation("session","handle");}
    @Test void persistedProductionJobIdAfterBackendRestartClosesRetainedSession(){var op=operation("START");op.put("phase","VERIFYING");var job=job();job.put("flinkJobId",REMOTE);job.put("sessionHandle","session");job.put("operationHandle","handle");bind(op,job);when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of());advance();assertEquals("SUCCESS",op.get("status"));assertEquals("RUNNING",job.get("status"));assertEquals("COMPLETED",job.get("gatewayCleanupStatus"));assertFalse(job.containsKey("sessionHandle"));assertFalse(job.containsKey("operationHandle"));verify(gateway).closeSession("session");verify(gateway,never()).statement(anyString(),anyString());}
    @Test void productionSessionCloseFailureDoesNotBlockRunningAndRefreshRetriesCleanup(){var op=operation("START");op.put("phase","VERIFYING");var job=job();job.put("flinkJobId",REMOTE);job.put("sessionHandle","session");job.put("operationHandle","handle");job.put("snapshot",Map.of());bind(op,job);when(gateway.job(REMOTE)).thenReturn(Map.of("state","RUNNING"));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of());doThrow(new StudioException("FLINK_REQUEST_FAILED","gateway unreachable",502)).doNothing().when(gateway).closeSession("session");advance();assertEquals("SUCCESS",op.get("status"));assertEquals("RUNNING",job.get("status"));assertEquals("PENDING",job.get("gatewayCleanupStatus"));assertEquals("session",job.get("sessionHandle"));assertEquals("handle",job.get("operationHandle"));when(compiler.compile(anyMap(),anyString())).thenReturn(new RealtimeSqlCompiler.Prepared(List.of(),"",List.of(),Map.of(),List.of(),"",Set.of()));when(gateway.checkpointConfig(REMOTE)).thenReturn(Map.of());when(gateway.metrics(REMOTE)).thenReturn(Map.of("inputRate",17));when(gateway.logs(REMOTE)).thenReturn(Map.of("nodes",List.of(),"exceptions",Map.of()));service.detail(W,"job");assertEquals("RUNNING",job.get("status"));assertEquals("COMPLETED",job.get("gatewayCleanupStatus"));assertFalse(job.containsKey("sessionHandle"));assertFalse(job.containsKey("operationHandle"));assertFalse(job.containsKey("gatewayCleanupMessage"));assertEquals(Map.of("inputRate",17),job.get("metrics"));verify(gateway,times(2)).closeSession("session");}
    @Test void unknownProductionSubmissionRetainsGatewayHandlesForReconciliation(){var job=job();job.put("submissionAttempted",true);job.put("sessionHandle","session");job.put("operationHandle","handle");ReflectionTestUtils.invokeMethod(service,"closeJobSession",job);assertEquals("session",job.get("sessionHandle"));assertEquals("handle",job.get("operationHandle"));verify(gateway,never()).closeSession(anyString());verify(repo,never()).saveJob(anyMap());}
    @Test void truncatedValidationErrorCannotProveSubmissionWasRejected(){assertFalse(Boolean.TRUE.equals(ReflectionTestUtils.invokeMethod(RealtimeService.class,"definiteSqlRejection","org.apache.flink.table.api.ValidationException: bad schema [truncated]")));}
    @Test void targetSchemaMismatchStopsSubmissionBeforeOpeningGatewaySession(){var op=operation("START");op.put("phase","QUEUED");var job=job();bind(op,job);var binding=Map.<String,Object>of("id","sink","connector","MYSQL_JDBC","role","SINK","datasourceId","ds","physicalTable","target");var snapshot=Map.<String,Object>of("workspaceId",W,"bindings",List.of(binding));when(repo.release("release",W)).thenReturn(Map.of("snapshot",snapshot,"datasourceBindings",List.of()));when(compiler.compile(anyMap(),anyString())).thenReturn(new RealtimeSqlCompiler.Prepared(List.of(),"INSERT INTO target SELECT * FROM source",List.of(),Map.of(),List.of(),"",Set.of()));doThrow(StudioException.bad("TARGET_SCHEMA_MISMATCH","目标唯一键不匹配")).when(sources).validateRealtimeTable(binding,W);advance();assertEquals("FAILED",op.get("status"));assertEquals("TARGET_SCHEMA_MISMATCH",op.get("errorCode"));assertEquals("FAILED",job.get("status"));verify(gateway,never()).openSession(anyMap());verify(gateway,never()).statement(anyString(),anyString());verify(repo).releaseActive("task","job");}
    @Test void retainedSafeInitializingSessionMustCloseBeforeNewSessionCanReplaceIt(){var op=operation("START");op.put("phase","INITIALIZING");var job=job();job.put("sessionHandle","old-session");job.put("submissionAttempted",false);bind(op,job);doThrow(new StudioException("FLINK_REQUEST_FAILED","cleanup unavailable",502)).when(gateway).closeSession("old-session");advance();assertEquals("RECOVERING",op.get("status"));assertEquals("GATEWAY_CLEANUP_PENDING",op.get("errorCode"));assertEquals("PENDING",job.get("gatewayCleanupStatus"));assertEquals("old-session",job.get("sessionHandle"));verify(gateway,never()).openSession(anyMap());verify(gateway,never()).statement(anyString(),anyString());verify(repo,never()).releaseActive(anyString(),anyString());}
    @Test void failedInitializationRetainsClosedResourceStateForBackgroundRetry(){var op=operation("START");op.put("phase","QUEUED");var job=job();bind(op,job);when(repo.release("release",W)).thenReturn(Map.of("snapshot",Map.of(),"datasourceBindings",List.of()));when(compiler.compile(anyMap(),anyString())).thenReturn(new RealtimeSqlCompiler.Prepared(List.of("CREATE TABLE source (id INT) WITH ('connector'='kafka')"),"INSERT INTO target SELECT * FROM source",List.of(),Map.of(),List.of(),"",Set.of()));when(gateway.openSession(anyMap())).thenReturn("session");when(gateway.execute(eq("session"),anyString())).thenThrow(StudioException.bad("FLINK_SQL_INVALID","org.apache.flink.table.api.ValidationException: bad DDL"));doThrow(new StudioException("FLINK_REQUEST_FAILED","cleanup unavailable",502)).doNothing().when(gateway).closeSession("session");advance();assertEquals("FAILED",op.get("status"));assertEquals("FAILED",job.get("status"));assertEquals("PENDING",job.get("gatewayCleanupStatus"));assertEquals("session",job.get("sessionHandle"));assertFalse(Boolean.TRUE.equals(job.get("submissionAttempted")));ReflectionTestUtils.invokeMethod(service,"closeJobSession",job);assertEquals("COMPLETED",job.get("gatewayCleanupStatus"));assertFalse(job.containsKey("sessionHandle"));verify(gateway,never()).statement(anyString(),anyString());}
    @Test void finiteJobUsesRemoteStartAndEndTimeInsteadOfGrowingWallClockDuration(){var op=operation("START");var job=job();job.put("flinkJobId",REMOTE);bind(op,job);long started=java.time.Instant.parse("2026-10-01T00:00:00Z").toEpochMilli();when(gateway.job(REMOTE)).thenReturn(Map.of("state","FINISHED","start-time",started,"end-time",started+1200,"duration",1200));when(gateway.checkpoints(REMOTE)).thenReturn(Map.of());advance();assertEquals("2026-10-01T00:00:00Z",job.get("startedAt"));assertEquals("2026-10-01T00:00:01.200Z",job.get("stoppedAt"));assertEquals(1200L,job.get("durationMs"));assertEquals("FINISHED",job.get("status"));}
    @Test void cdcRangeConflictFailsProductionBeforeOpeningGatewayOrSubmittingSql(){
        var op=operation("START");op.put("phase","QUEUED");var job=job();bind(op,job);
        when(repo.release("release",W)).thenReturn(Map.of("snapshot",Map.of("workspaceId",W),"datasourceBindings",List.of()));
        var prepared=new RealtimeSqlCompiler.Prepared(List.of(),"INSERT INTO target SELECT * FROM source",List.of(),Map.of(),List.of(),"",Set.of());
        var ranges=List.<Map<String,Object>>of(Map.of("endpoint","mysql:3306","first",5401L,"last",5656L,"tableName","source"));
        when(compiler.compile(anyMap(),eq(REMOTE))).thenReturn(prepared);when(compiler.cdcServerIds(prepared)).thenReturn(ranges);
        doThrow(StudioException.conflict("CDC_SERVER_ID_IN_USE","CDC范围已占用")).when(repo).reserveCdcServerIds("JOB","job",REMOTE,ranges);
        advance();assertEquals("FAILED",op.get("status"));assertEquals("CDC_SERVER_ID_IN_USE",op.get("errorCode"));assertEquals("FAILED",job.get("status"));
        verify(gateway,never()).openSession(anyMap());verify(gateway,never()).statement(anyString(),anyString());verify(repo).releaseActive("task","job");
    }
    @Test void cdcRangeConflictFailsPreviewBeforeOpeningGatewayOrSubmittingSelect(){
        var op=operation("PREVIEW");when(repo.operation("op",W)).thenReturn(op);
        var p=new LinkedHashMap<String,Object>(Map.of("id",REMOTE,"workspaceId",W,"task",Map.of(),"query","SELECT * FROM source","operationId","op","pipelineName","sinket_preview","status","STARTING","deadline",java.time.Instant.now().plusSeconds(30).toString()));
        when(repo.preview(REMOTE,W)).thenReturn(p);
        var prepared=new RealtimeSqlCompiler.Prepared(List.of(),"",List.of("SELECT * FROM source"),Map.of(),List.of(),"",Set.of());
        var ranges=List.<Map<String,Object>>of(Map.of("endpoint","mysql:3306","first",7001L,"last",7256L,"tableName","source"));
        when(compiler.compilePreview(anyMap(),eq(REMOTE),anyString())).thenReturn(prepared);when(compiler.cdcServerIds(prepared)).thenReturn(ranges);
        doThrow(StudioException.conflict("CDC_SERVER_ID_IN_USE","CDC范围已占用")).when(repo).reserveCdcServerIds("PREVIEW",REMOTE,REMOTE,ranges);
        ReflectionTestUtils.invokeMethod(service,"advancePreview",REMOTE,W);
        assertEquals("FAILED",p.get("status"));assertEquals("CDC_SERVER_ID_IN_USE",p.get("errorCode"));assertEquals("FAILED",op.get("status"));
        verify(gateway,never()).openSession(anyMap());verify(gateway,never()).statement(anyString(),anyString());
        verify(repo,never()).releaseCdcServerIds(eq("JOB"),anyString(),anyString());
    }
    @Test void cdcReservationsStayHeldForUnknownRunningStoppingOrPendingCleanup(){
        for(String status:List.of("STARTING","RUNNING","RESTARTING","STOPPING")){var value=job();value.put("status",status);value.put("flinkJobId",REMOTE);assertFalse(Boolean.TRUE.equals(ReflectionTestUtils.invokeMethod(service,"releaseCdcIfSafe",value)));}
        var unknown=job();unknown.put("status","FAILED");unknown.put("submissionAttempted",true);assertFalse(Boolean.TRUE.equals(ReflectionTestUtils.invokeMethod(service,"releaseCdcIfSafe",unknown)));
        var unconfirmed=job();unconfirmed.put("status","STOPPED");unconfirmed.put("flinkJobId",REMOTE);assertFalse(Boolean.TRUE.equals(ReflectionTestUtils.invokeMethod(service,"releaseCdcIfSafe",unconfirmed)));
        var pending=job();pending.put("status","FINISHED");pending.put("flinkJobId",REMOTE);pending.put("remoteTerminalConfirmed",true);pending.put("gatewayCleanupStatus","PENDING");assertFalse(Boolean.TRUE.equals(ReflectionTestUtils.invokeMethod(service,"releaseCdcIfSafe",pending)));
        verify(repo,never()).releaseCdcServerIds(anyString(),anyString(),anyString());
        pending.put("gatewayCleanupStatus","COMPLETED");assertTrue(Boolean.TRUE.equals(ReflectionTestUtils.invokeMethod(service,"releaseCdcIfSafe",pending)));verify(repo).releaseCdcServerIds("JOB","job",REMOTE);
    }
    @Test void terminalCdcBackgroundReconciliationRetriesCleanupAfterRestartWithoutBrowserReads(){
        var value=job();value.put("status","FAILED");value.put("flinkJobId",REMOTE);value.put("sessionHandle","session");value.put("operationHandle","handle");
        when(gateway.job(REMOTE)).thenReturn(Map.of("state","CANCELED"));doThrow(new StudioException("FLINK_REQUEST_FAILED","cleanup unavailable",502)).doNothing().when(gateway).closeSession("session");
        ReflectionTestUtils.invokeMethod(service,"reconcileTerminalCdcJob",value);
        assertEquals(true,value.get("remoteTerminalConfirmed"));assertEquals("PENDING",value.get("gatewayCleanupStatus"));verify(repo,never()).releaseCdcServerIds(anyString(),anyString(),anyString());
        service.close();service=new RealtimeService(repo,objects,sources,compiler,gateway,new JsonCodec(),new TransactionTemplate(mock(PlatformTransactionManager.class)),false);
        ReflectionTestUtils.invokeMethod(service,"reconcileTerminalCdcJob",value);assertEquals("COMPLETED",value.get("gatewayCleanupStatus"));
        verify(repo).releaseCdcServerIds("JOB","job",REMOTE);verify(gateway,times(1)).job(REMOTE);verify(gateway,times(2)).closeSession("session");
    }
    @Test void previewCdcRangeIsReleasedOnlyAfterTerminalAndSuccessfulGatewayCleanup(){
        var op=operation("PREVIEW");when(repo.operation("op",W)).thenReturn(op);
        var p=new LinkedHashMap<String,Object>(Map.of("id",REMOTE,"workspaceId",W,"operationId","op","flinkJobId",REMOTE,"querySubmissionAttempted",true,"sessionHandle","session","operationHandle","handle","rows",List.of()));
        when(gateway.job(REMOTE)).thenReturn(Map.of("state","CANCELED"));doThrow(new StudioException("FLINK_REQUEST_FAILED","cleanup unavailable",502)).doNothing().when(gateway).closeSession("session");
        ReflectionTestUtils.invokeMethod(service,"endPreview",p,"SUCCESS",false);assertEquals("PENDING",p.get("cleanupStatus"));verify(repo,never()).releaseCdcServerIds(anyString(),anyString(),anyString());
        ReflectionTestUtils.invokeMethod(service,"endPreview",p,"CANCELLED",true);assertEquals("COMPLETED",p.get("cleanupStatus"));assertEquals("SUCCESS",p.get("status"));verify(repo).releaseCdcServerIds("PREVIEW",REMOTE,REMOTE);
    }
    @Test void previewCdcRangeCannotReleaseFromJobNotFoundAndEmptyOverviewAlone(){
        var p=new LinkedHashMap<String,Object>(Map.of("id",REMOTE,"workspaceId",W,"operationId","op","flinkJobId",REMOTE,"querySubmissionAttempted",true,"sessionHandle","session","operationHandle","handle","rows",List.of()));
        when(gateway.job(REMOTE)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","job unavailable",404));when(gateway.jobsOverview()).thenReturn(Map.of("jobs",List.of()));
        ReflectionTestUtils.invokeMethod(service,"endPreview",p,"SUCCESS",false);assertEquals("PENDING",p.get("cleanupStatus"));assertEquals("CANCELLING",p.get("status"));verify(repo,never()).releaseCdcServerIds(anyString(),anyString(),anyString());
    }
    @Test void clearlyRejectedPreviewReleasesCdcRangeAfterIdentityCheckAndCleanup(){
        var op=operation("PREVIEW");when(repo.operation("op",W)).thenReturn(op);
        var p=new LinkedHashMap<String,Object>(Map.of("id",REMOTE,"workspaceId",W,"operationId","op","pipelineName","sinket_preview","status","RUNNING","querySubmissionAttempted",true,"sessionHandle","session","operationHandle","handle","deadline",java.time.Instant.now().plusSeconds(30).toString()));
        when(repo.preview(REMOTE,W)).thenReturn(p);when(gateway.result("session","handle",0)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","org.apache.flink.table.api.ValidationException: invalid SELECT",502));
        when(gateway.findJobByName("sinket_preview")).thenReturn(Map.of());when(gateway.job(REMOTE)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","job not found",404));
        doThrow(new StudioException("FLINK_REQUEST_FAILED","cleanup unavailable",502)).doNothing().when(gateway).closeSession("session");
        ReflectionTestUtils.invokeMethod(service,"advancePreview",REMOTE,W);assertEquals("PENDING",p.get("cleanupStatus"));assertFalse(p.containsKey("operationHandle"));verify(repo,never()).releaseCdcServerIds(anyString(),anyString(),anyString());
        ReflectionTestUtils.invokeMethod(service,"advancePreview",REMOTE,W);assertEquals("FAILED",p.get("status"));assertEquals("COMPLETED",p.get("cleanupStatus"));
        var ordered=inOrder(gateway,repo);ordered.verify(gateway).job(REMOTE);ordered.verify(gateway).closeSession("session");ordered.verify(repo).releaseCdcServerIds("PREVIEW",REMOTE,REMOTE);
    }
    @Test void ambiguousPreviewGatewayErrorRetainsCdcRangeDespiteClosingKnownHandles(){
        var p=new LinkedHashMap<String,Object>(Map.of("id",REMOTE,"workspaceId",W,"operationId","op","pipelineName","sinket_preview","status","RUNNING","querySubmissionAttempted",true,"sessionHandle","session","operationHandle","handle","deadline",java.time.Instant.now().plusSeconds(30).toString()));
        when(repo.preview(REMOTE,W)).thenReturn(p);when(gateway.result("session","handle",0)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","TimeoutException: submitJob response lost",502));
        when(gateway.findJobByName("sinket_preview")).thenReturn(Map.of());when(gateway.job(REMOTE)).thenThrow(new StudioException("FLINK_REQUEST_FAILED","job not found",404));
        ReflectionTestUtils.invokeMethod(service,"advancePreview",REMOTE,W);assertEquals("CANCELLING",p.get("status"));assertEquals("PENDING",p.get("cleanupStatus"));assertFalse(Boolean.TRUE.equals(p.get("submissionRejected")));
        verify(gateway).closeSession("session");verify(repo,never()).releaseCdcServerIds(anyString(),anyString(),anyString());
    }
    @Test void previewRestartAfterResourceCleanupAndReleasedRangeNeverResubmitsQuery(){
        var op=operation("PREVIEW");when(repo.operation("op",W)).thenReturn(op);
        var p=new LinkedHashMap<String,Object>(Map.of("id",REMOTE,"workspaceId",W,"operationId","op","flinkJobId",REMOTE,"status","RUNNING","querySubmissionAttempted",true,"sessionHandle","session","operationHandle","handle","rows",List.of()));
        var stored=new AtomicReference<Map<String,Object>>(new LinkedHashMap<>(p));var rejectFinalWrite=new java.util.concurrent.atomic.AtomicBoolean(true);
        when(repo.preview(REMOTE,W)).thenAnswer(invocation->new LinkedHashMap<>(stored.get()));
        doAnswer(invocation->{Map<String,Object> next=invocation.getArgument(0);if("SUCCESS".equals(next.get("status"))&&rejectFinalWrite.get())throw new IllegalStateException("final preview write interrupted");stored.set(new LinkedHashMap<>(next));return null;}).when(repo).savePreview(anyMap());
        when(gateway.job(REMOTE)).thenReturn(Map.of("state","CANCELED"));
        assertThrows(IllegalStateException.class,()->ReflectionTestUtils.invokeMethod(service,"endPreview",p,"SUCCESS",false));
        assertEquals("CANCELLING",stored.get().get("status"));assertEquals("SUCCESS",stored.get().get("pendingFinalStatus"));assertFalse(stored.get().containsKey("sessionHandle"));
        verify(repo).releaseCdcServerIds("PREVIEW",REMOTE,REMOTE);
        service.close();service=new RealtimeService(repo,objects,sources,compiler,gateway,new JsonCodec(),new TransactionTemplate(mock(PlatformTransactionManager.class)),false);rejectFinalWrite.set(false);
        ReflectionTestUtils.invokeMethod(service,"advancePreview",REMOTE,W);assertEquals("SUCCESS",stored.get().get("status"));assertEquals("COMPLETED",stored.get().get("cleanupStatus"));
        verify(gateway,never()).openSession(anyMap());verify(gateway,never()).statement(anyString(),anyString());verify(compiler,never()).compilePreview(anyMap(),anyString(),anyString());
    }
    @Test void invalidSuccessfulPostResponseRemainsRecoveringAcrossRestartWithoutResubmitting(){
        var op=operation("START");op.put("phase","QUEUED");var value=job();bind(op,value);
        when(repo.release("release",W)).thenReturn(Map.of("snapshot",Map.of("workspaceId",W),"datasourceBindings",List.of()));
        var prepared=new RealtimeSqlCompiler.Prepared(List.of(),"INSERT INTO target SELECT * FROM source",List.of(),Map.of(),List.of(),"",Set.of());when(compiler.compile(anyMap(),eq(REMOTE))).thenReturn(prepared);
        var ranges=List.<Map<String,Object>>of(Map.of("endpoint","mysql:3306","first",5401L,"last",5656L,"tableName","source"));when(compiler.cdcServerIds(prepared)).thenReturn(ranges);
        when(gateway.openSession(anyMap())).thenReturn("session");when(gateway.statement("session",prepared.execution())).thenThrow(new StudioException("FLINK_PROTOCOL_ERROR","SQL Gateway 未返回有效操作 ID，提交结果需先对账",502));when(gateway.findJobByName("sinket_test")).thenReturn(Map.of());
        advance();assertEquals("RECOVERING",op.get("status"));assertEquals("FLINK_PROTOCOL_ERROR",op.get("errorCode"));assertEquals(true,value.get("submissionAttempted"));assertFalse(value.containsKey("operationHandle"));
        service.close();service=new RealtimeService(repo,objects,sources,compiler,gateway,new JsonCodec(),new TransactionTemplate(mock(PlatformTransactionManager.class)),false);
        advance();advance();assertEquals("RECOVERING",op.get("status"));assertEquals("RECONCILING",op.get("phase"));
        verify(repo,times(1)).reserveCdcServerIds("JOB","job",REMOTE,ranges);verify(gateway,times(1)).openSession(anyMap());verify(gateway,times(1)).statement("session",prepared.execution());verify(gateway,times(2)).findJobByName("sinket_test");
        verify(gateway,never()).closeSession(anyString());verify(repo,never()).releaseActive(anyString(),anyString());verify(repo,never()).releaseCdcServerIds(anyString(),anyString(),anyString());
    }
}
